import assert from 'node:assert/strict';
import {execFileSync} from 'node:child_process';
import {randomUUID} from 'node:crypto';
import {readFile} from 'node:fs/promises';
import {Pool} from 'pg';
import {drizzle} from 'drizzle-orm/node-postgres';
import {sql} from 'drizzle-orm';
import {defineAuthorization,type AuthorizationContext} from '../../../src/integrations/authorization/authorization.server';
import {authorizationAssignments} from '../../../src/integrations/authorization/schema';
import {pageInput} from '../../../src/integrations/authorization/validation';
const name=`authorization-contract-${randomUUID()}`;
const docker=(...args:string[])=>execFileSync('docker',args,{encoding:'utf8',stdio:['ignore','pipe','pipe']});
let pool:Pool|undefined;
try{
 docker('run','-d','--name',name,'-e','POSTGRES_USER=fixture','-e','POSTGRES_PASSWORD=fixture','-e','POSTGRES_DB=fixture','-p','127.0.0.1::5432','public.ecr.aws/docker/library/postgres:18.1-alpine@sha256:aa6eb304ddb6dd26df23d05db4e5cb05af8951cda3e0dc57731b771e0ef4ab29');
 const port=docker('port',name,'5432/tcp').trim().split(':').at(-1);
 pool=new Pool({connectionString:`postgresql://fixture:fixture@127.0.0.1:${port}/fixture`,connectionTimeoutMillis:1000,idleTimeoutMillis:1000});
 for(let i=0;;i++){try{await pool.query('SELECT 1');break;}catch{if(i>=30)throw new Error('Fixture readiness failed');await new Promise(r=>setTimeout(r,200));}}
 await pool.query(await readFile('capabilities/authorization/test/schema.sql','utf8'));
 await pool.query('CREATE TABLE fixture_membership (tenant_id text,user_id text,PRIMARY KEY(tenant_id,user_id)); CREATE TABLE fixture_audit (action text, subject_id text); CREATE TABLE fixture_note (id text PRIMARY KEY,title text); INSERT INTO fixture_membership VALUES (\'tenant-a\',\'alice\'); INSERT INTO fixture_note VALUES (\'note\',\'old\')');
 const db=drizzle(pool),alice:AuthorizationContext={userId:'alice',scope:{kind:'user',id:'alice'}},bob:AuthorizationContext={userId:'bob',scope:{kind:'user',id:'bob'}},tenant:AuthorizationContext={userId:'alice',scope:{kind:'tenant',id:'tenant-a'}};
 const registry={actions:[{id:'notes.read'},{id:'notes.write',resource:(context:AuthorizationContext,resource:unknown)=>(resource as {owner?:string}).owner===context.userId}],roles:[{id:'reader',actions:['notes.read']},{id:'writer',actions:['notes.write']}]};
 const auth=defineAuthorization(registry,{managementGuard:actor=>actor.userId==='alice',tenantMembership:async(userId,tenantId,tx)=>{const result=await tx.execute(sql`SELECT 1 FROM fixture_membership WHERE tenant_id=${tenantId} AND user_id=${userId} FOR SHARE`);return result.rows.length>0;},audit:async(tx,event)=>{await tx.execute(sql`INSERT INTO fixture_audit VALUES (${event.action},${event.subjectId})`);}});
 assert.throws(()=>defineAuthorization({...registry,roles:[{id:'reader',actions:['missing.action']}]}));
 assert.throws(()=>defineAuthorization({...registry,actions:[{id:'notes.read'},{id:'notes.read'}]}));
 assert.equal(await auth.can(db,alice,'notes.read'),false);
 assert.equal((await auth.authorize(db,{scope:alice.scope},'notes.read')).reason,'unauthenticated');
 assert.equal((await auth.authorize(db,alice,'unknown.action')).reason,'unknown-action');
 await assert.rejects(defineAuthorization(registry).grantRole(db,alice,{scope:alice.scope,userId:'alice',roleId:'reader'}),{code:'forbidden'});
 const grant={scope:alice.scope,userId:'alice',roleId:'reader'};
 const grants=await Promise.all([auth.grantRole(db,alice,grant),auth.grantRole(db,alice,grant)]);assert.equal(grants.filter(g=>g.changed).length,1);
 assert.equal(await auth.can(db,alice,'notes.read'),true);assert.equal(await auth.can(db,bob,'notes.read'),false);
 assert.equal(await auth.can(db,{...alice,scope:bob.scope},'notes.read'),false);
 await auth.grantRole(db,alice,{...grant,roleId:'writer'});
 assert.equal(await auth.can(db,alice,'notes.write',{owner:'alice'}),true);assert.equal(await auth.can(db,alice,'notes.write',{owner:'bob'}),false);assert.equal(await auth.can(db,alice,'notes.write'),false);
 assert.equal(await auth.can(db,{...alice,credentialAllows:()=>false},'notes.read'),false);
 assert.equal(await auth.can(db,{...bob,credentialAllows:()=>true},'notes.read'),false);
 const page=await auth.listAssignments(db,alice,alice.scope,{limit:1});assert.equal(page.items.length,1);assert.ok(page.nextCursor);assert.equal((await auth.listAssignments(db,alice,alice.scope,{limit:1,cursor:page.nextCursor})).items.length,1);
 assert.throws(()=>pageInput({cursor:`${page.nextCursor}=`}));assert.throws(()=>pageInput({limit:101}));
 const auditBefore=(await pool.query('SELECT count(*)::int AS count FROM fixture_audit')).rows[0].count;
 await assert.rejects(db.transaction(async tx=>{await auth.grantRoleInTransaction(tx,alice,{scope:bob.scope,userId:'bob',roleId:'reader'});throw new Error('fixture rollback');}));assert.equal(await auth.can(db,bob,'notes.read'),false);assert.equal((await pool.query('SELECT count(*)::int AS count FROM fixture_audit')).rows[0].count,auditBefore);
 const tenantGrant={scope:tenant.scope,userId:'alice',roleId:'reader'};await auth.grantRole(db,alice,tenantGrant);assert.equal(await auth.can(db,tenant,'notes.read'),true);
 await pool.query("DELETE FROM fixture_membership");assert.equal(await auth.can(db,tenant,'notes.read'),false);assert.equal((await db.select().from(authorizationAssignments)).length,3);
 assert.equal(await defineAuthorization(registry).can(db,tenant,'notes.read'),false);
 await auth.revokeRole(db,alice,grant);assert.equal(await auth.can(db,alice,'notes.read'),false);assert.equal((await auth.revokeRole(db,alice,grant)).changed,false);
 await db.insert(authorizationAssignments).values({id:randomUUID(),scopeKind:'user',scopeId:'bob',userId:'bob',roleId:'removed',createdAt:new Date()});assert.equal(await auth.can(db,bob,'notes.read'),false);
 await auth.revokeRole(db,alice,{scope:bob.scope,userId:'bob',roleId:'removed'});assert.equal((await auth.revokeRole(db,alice,{scope:bob.scope,userId:'bob',roleId:'removed'})).changed,false);
 const mapped=defineAuthorization(registry,{mappedRoles:context=>context.userId==='bob'?['reader']:[]});assert.equal(await mapped.can(db,bob,'notes.read'),true);assert.equal(await mapped.can(db,alice,'notes.read'),false);
 await auth.grantRole(db,alice,grant);
 let acquired!:()=>void,release!:()=>void;const started=new Promise<void>(r=>acquired=r),hold=new Promise<void>(r=>release=r);
 const write=db.transaction(async tx=>{await auth.requirePermissionInTransaction(tx,alice,'notes.read');acquired();await hold;await tx.execute(sql`UPDATE fixture_note SET title='new' WHERE id='note'`);});await started;
 let revoked=false;const revoke=auth.revokeRole(db,alice,grant).then(()=>{revoked=true;});await new Promise(r=>setTimeout(r,100));assert.equal(revoked,false);release();await Promise.all([write,revoke]);assert.equal(await auth.can(db,alice,'notes.read'),false);
 assert.equal((await pool.query('SELECT title FROM fixture_note')).rows[0].title,'new');
 const snapshot=await Promise.all([auth.authorize(db,alice,'notes.write',{owner:'alice'}),auth.authorize(db,bob,'notes.write',{owner:'alice'})]);assert.equal(snapshot[0].allowed,true);assert.equal(snapshot[1].allowed,false);
 const client=await pool.connect();await client.query('BEGIN');await client.query('LOCK TABLE authorization_assignment IN ACCESS EXCLUSIVE MODE');const timed=await auth.authorize(db,alice,'notes.write',{owner:'alice'});assert.equal(timed.allowed,false);assert.equal(timed.errorCode,'timeout');await client.query('ROLLBACK');client.release();
 await pool.end();pool=undefined;docker('stop',name);pool=new Pool({connectionString:`postgresql://fixture:fixture@127.0.0.1:${port}/fixture`,connectionTimeoutMillis:1000});const offline=drizzle(pool);const unavailable=await auth.authorize(offline,alice,'notes.read');assert.equal(unavailable.reason,'error');assert.equal(unavailable.errorCode,'unavailable');assert.equal(await auth.can(offline,alice,'notes.read'),false);await assert.rejects(auth.requirePermission(offline,alice,'notes.read'),{code:'unavailable'});
 console.log('Authorization PostgreSQL contract passed: exact scopes, union, fail closed, transactional management, revoke/write locking.');
}finally{await pool?.end();try{docker('rm','-f',name);}catch{}}
