// @vitest-environment jsdom
import { afterEach, expect, test } from "vitest";
import { cleanup, fireEvent, render, screen, within } from "@testing-library/react";
import { act } from "react";
import { hydrateRoot } from "react-dom/client";
import { renderToString } from "react-dom/server";
import { Example } from "../.add-on/assets/scripts/data-table-example";
afterEach(cleanup);
Object.assign(globalThis, {IS_REACT_ACT_ENVIRONMENT:true});
test("native v9 controlled and internal slices, grouped headers and manual mode", () => {
 render(<Example />);
 const table = () => within(screen.getByRole("table",{name:"People"}));
 const names = () => Array.from(screen.getByRole("table",{name:"People"}).querySelectorAll("tbody tr")).map(row => row.textContent);
 expect(names()).toEqual(["Ada30","Bea10"]);
 fireEvent.click(table().getByRole("button",{name:"Score"}));
 expect(names()).toEqual(["Ada30","Cy20"]);
 fireEvent.click(table().getByRole("button",{name:"Score"}));
 expect(names()).toEqual(["Bea10","Cy20"]);
 fireEvent.click(table().getByRole("button",{name:"Name"}));
 fireEvent.click(table().getByRole("button",{name:"Name"}));
 expect(names()).toEqual(["Cy20","Bea10"]);
 expect(table().getByRole("columnheader",{name:"Name"}).getAttribute("aria-sort")).toBe("descending");
 fireEvent.click(table().getByRole("checkbox",{name:"Select Cy"}));
 fireEvent.click(screen.getByRole("button",{name:"Next"}));
 expect(names()).toEqual(["Ada30"]);
 fireEvent.click(screen.getByRole("button",{name:"Previous"}));
 expect((table().getByRole("checkbox",{name:"Select Cy"}) as HTMLInputElement).checked).toBe(true);
 fireEvent.change(screen.getByLabelText("Filter"),{target:{value:"Bea"}});
 expect(names()).toEqual(["Bea10"]);
 fireEvent.change(screen.getByLabelText("Filter"),{target:{value:"missing"}});
 expect(names()).toEqual(["No results."]);
 fireEvent.change(screen.getByLabelText("Filter"),{target:{value:""}});
 fireEvent.click(screen.getByRole("button",{name:"Toggle score"}));
 expect(table().queryByRole("columnheader",{name:"Score"})).toBeNull();
 fireEvent.click(screen.getByRole("button",{name:"Toggle score"}));
 fireEvent.click(screen.getByRole("button",{name:"Toggle table"}));
 fireEvent.click(screen.getByRole("button",{name:"Toggle table"}));
 expect((table().getByRole("checkbox",{name:"Select Cy"}) as HTMLInputElement).checked).toBe(true);
 fireEvent.click(screen.getByRole("button",{name:"Toggle manual"}));
 fireEvent.change(screen.getByLabelText("Filter"),{target:{value:"missing"}});
 expect(names()).toEqual(["Ada30","Bea10","Cy20"]);
 fireEvent.click(screen.getByRole("button",{name:"Next"}));
 expect(screen.getByLabelText("Page").textContent).toBe("2");
 expect(names()).toEqual(["Ada30","Bea10","Cy20"]);
 const internal=within(screen.getByRole("table",{name:"Uncontrolled"}));
 fireEvent.click(internal.getByRole("button",{name:"Name"}));
 fireEvent.click(internal.getByRole("button",{name:"Name"}));
 expect(screen.getByRole("table",{name:"Uncontrolled"}).querySelector("tbody tr")?.textContent).toBe("Cy20");
});
test("SSR markup hydrates without recoverable errors", async () => {
 const container=document.createElement("div");
 container.innerHTML=renderToString(<Example />);
 document.body.append(container);
 const errors:unknown[]=[];
 let root:ReturnType<typeof hydrateRoot>;
 await act(async () => {root=hydrateRoot(container,<Example />,{onRecoverableError:error => errors.push(error)});});
 expect(container.querySelectorAll("thead tr").length).toBe(4);
 expect(errors).toEqual([]);
 await act(async () => root.unmount());
 container.remove();
});
