import assert from 'node:assert/strict';
import { readFileSync } from 'node:fs';
import { cacheableResponse,eligibleNavigation,validBase,validPublicPath,cachePrefix } from '../src/integrations/pwa-offline/policy';
import { createPwaController } from '../src/integrations/pwa-offline/client';
for(const base of ['/','/demo/','/nested/app/']) assert.ok(validBase(base));
for(const base of ['https://example.test/','//else/','/x/../','/x?y/']) assert.equal(validBase(base),false);
for(const path of ['app/account','api/private','auth','uploads/x','../x','x?y','/pwa-test']) assert.equal(validPublicPath(path),false);
const safe={status:200,type:'basic',redirected:false,url:'https://example.test/pwa-offline/offline.html',headers:new Headers({'content-type':'text/html; charset=utf-8','cache-control':'public, max-age=300'})} as Response;
assert.ok(cacheableResponse(safe,safe.url,true));
for(const patch of [{status:401},{status:500},{type:'opaque'},{redirected:true},{url:'https://evil.test'},{headers:new Headers({'content-type':'text/html','cache-control':'private'})},{headers:new Headers({'content-type':'text/html','cache-control':'no-store'})},{headers:new Headers({'content-type':'text/html','vary':'Cookie'})},{headers:new Headers({'content-type':'text/html','vary':'Authorization'})},{headers:new Headers({'content-type':'text/html','vary':'*'})},{headers:new Headers({'content-type':'application/json'})}]) assert.equal(cacheableResponse({...safe,...patch} as Response,safe.url,true),false);
assert.equal(cacheableResponse({...safe,headers:new Headers({'content-type':'image/png','cache-control':'x-public, x-immutable'})} as Response,safe.url,false),false);
assert.equal(cacheableResponse({...safe,headers:new Headers({'content-type':'image/png','cache-control':'public, immutable, public'})} as Response,safe.url,false),false);
for(const value of ['note="x,public,immutable,z"','public=0, immutable','public, immutable=0']) assert.equal(cacheableResponse({...safe,headers:new Headers({'content-type':'image/png','cache-control':value})} as Response,safe.url,false),false);
const req=(url:string,method='GET',mode='navigate')=>({url,method,mode} as Request);
const scope=new URL('https://example.test/demo/');
assert.ok(eligibleNavigation(req('https://example.test/demo/pwa-test'),scope,['pwa-test']));
for(const request of [req('https://example.test/demo/pwa-test?a=1'),req('https://example.test/pwa-test'),req('https://example.test/demo/pwa-test','POST'),req('https://example.test/demo/pwa-test','GET','cors'),req('https://other.test/demo/pwa-test')]) assert.equal(eligibleNavigation(request,scope,['pwa-test']),false);
assert.equal(eligibleNavigation(req('https://example.test/demo/pwa-test'),scope,[]),false);
assert.notEqual(cachePrefix('https://example.test/'),cachePrefix(scope.href));
const worker=readFileSync('src/integrations/pwa-offline/pwa-offline-sw.ts','utf8');
assert.ok(!/\.(skipWaiting|claim|navigate)\(/.test(worker));
assert.match(worker,/credentials:\s*['"]omit['"]/);
assert.match(worker,/integrity:\s*entry.integrity/);
const target=new EventTarget();
Object.defineProperty(globalThis,'window',{value:Object.assign(target,{isSecureContext:true}),configurable:true});
Object.defineProperty(globalThis,'location',{value:{origin:'https://example.test'},configurable:true});
let calls=0;
const registration=Object.assign(new EventTarget(),{scope:'https://example.test/',active:{scriptURL:'https://example.test/pwa-offline-sw.js'},waiting:null,installing:null,update:async()=>{}});
const serviceWorker={getRegistrations:async()=>[] as unknown[],controller:null,register:async()=>{calls++;await Promise.resolve();return registration;}};
Object.defineProperty(globalThis,'navigator',{value:{serviceWorker,onLine:true},configurable:true});
const controller=createPwaController();const unsub=controller.subscribe(()=>{});const unsub2=controller.subscribe(()=>{});
await Promise.all([controller.register(),controller.register()]);assert.equal(calls,1);assert.equal(controller.getSnapshot().status,'ready');
target.dispatchEvent(new Event('beforeinstallprompt'));assert.equal(controller.getSnapshot().canInstall,false,'Synthetic install events cannot claim browser eligibility');
target.dispatchEvent(new Event('appinstalled'));assert.equal(controller.getSnapshot().installed,false);
unsub();unsub2();
serviceWorker.getRegistrations=async()=>[{...registration,active:{scriptURL:'https://example.test/foreign-sw.js'}}];
await controller.register();assert.equal(calls,1);assert.equal(controller.getSnapshot().status,'error');
console.info('PWA policy, privacy exclusions, base paths, owned registration and synthetic install rejection passed');

await import('./pwa-worker-unit');
