import assert from 'node:assert/strict';import {execFileSync} from 'node:child_process';import {randomUUID,createHash} from 'node:crypto';import {readFile} from 'node:fs/promises';import {Pool} from 'pg';import {drizzle} from 'drizzle-orm/node-postgres';import {defineFeatureFlags,rolloutBucket} from '../../../src/integrations/feature-flags/feature-flags.server';import {flagDefinitions} from '../../../src/integrations/feature-flags/schema';import {eq} from 'drizzle-orm';
const name=`feature-flags-contract-${randomUUID()}`;const docker=(...args:string[])=>execFileSync('docker',args,{encoding:'utf8',stdio:['ignore','pipe','pipe']});let pool:Pool|undefined;
try{
 docker('run','-d','--name',name,'-e','POSTGRES_USER=fixture','-e','POSTGRES_PASSWORD=fixture','-e','POSTGRES_DB=fixture','-p','127.0.0.1::5432','public.ecr.aws/docker/library/postgres:18.1-alpine@sha256:aa6eb304ddb6dd26df23d05db4e5cb05af8951cda3e0dc57731b771e0ef4ab29');const port=docker('port',name,'5432/tcp').trim().split(':').at(-1);const url=`postgresql://fixture:fixture@127.0.0.1:${port}/fixture`;pool=new Pool({connectionString:url,connectionTimeoutMillis:1000,idleTimeoutMillis:1000});for(let i=0;;i++){try{await pool.query('SELECT 1');break;}catch{if(i>=30)throw new Error('Fixture readiness failed');await new Promise(r=>setTimeout(r,200));}}
 await pool.query(await readFile('capabilities/feature-flags/test/schema.sql','utf8'));const db=drizzle(pool),flags=defineFeatureFlags({managementGuard:actor=>actor.authority==='operator'}),actor={userId:'fixture-operator',authority:'operator' as const},key='beta.dashboard';
 for(const [kind,id,prefix,bucket] of [['tenant','tenant-a','6e45aa45',4307],['tenant','tenant-b','c877e3e7',7830],['user','user-a','4a7f2566',2910],['user','user-b','9c644d5c',6109]] as const){assert.equal(createHash('sha256').update(JSON.stringify(['feature-flags-v1',key,kind,id])).digest('hex').slice(0,8),prefix);assert.equal(rolloutBucket(key,kind,id),bucket);}
 assert.equal(JSON.stringify(['feature-flags-v1','beta.unicode','user','é😀\n\u0001']), '["feature-flags-v1","beta.unicode","user","é😀\\n\\u0001"]');assert.equal(rolloutBucket('beta.unicode','user','é😀'),Math.floor(createHash('sha256').update('["feature-flags-v1","beta.unicode","user","é😀"]').digest().readUInt32BE(0)*10000/4294967296));
 assert.deepEqual(await flags.evaluateBooleanDetails(db,key,{}),{value:false,reason:'not-found'});await assert.rejects(defineFeatureFlags().createDefinition(db,actor,{key}),{code:'forbidden'});await assert.rejects(flags.evaluateBoolean(db,key,{userId:'bad\n'}),{code:'invalid-input'});await assert.rejects(flags.evaluateMany(db,[key,key],{}),{code:'invalid-input'});
 let row=await flags.createDefinition(db,actor,{key,defaultValue:true});assert.equal(row.revision,1);await assert.rejects(flags.createDefinition(db,actor,{key}),{code:'conflict'});assert.equal((await flags.evaluateBooleanDetails(db,key,{userId:'user-a'})).reason,'disabled');
 row=await flags.updateDefinition(db,actor,{key,expectedRevision:row.revision,enabled:true});assert.equal(await flags.evaluateBoolean(db,key,{}),true);const unchanged=await flags.updateDefinition(db,actor,{key,expectedRevision:row.revision,enabled:true});assert.equal(unchanged.revision,row.revision);await assert.rejects(flags.updateDefinition(db,actor,{key,expectedRevision:1,enabled:false}),{code:'conflict'});
 row=await flags.updateDefinition(db,actor,{key,expectedRevision:row.revision,rolloutBasisPoints:5000});for(const [kind,id,value] of [['tenant','tenant-a',true],['tenant','tenant-b',false],['user','user-a',true],['user','user-b',false]] as const)assert.equal(await flags.evaluateBoolean(db,key,kind==='tenant'?{tenantId:id}:{userId:id}),value);assert.equal((await flags.evaluateBooleanDetails(db,key,{})).reason,'default');
 row=await flags.updateDefinition(db,actor,{key,expectedRevision:row.revision,rolloutBasisPoints:4307});assert.equal(await flags.evaluateBoolean(db,key,{tenantId:'tenant-a'}),false);row=await flags.updateDefinition(db,actor,{key,expectedRevision:row.revision,rolloutBasisPoints:4308});assert.equal(await flags.evaluateBoolean(db,key,{tenantId:'tenant-a'}),true);
 for(const percent of [0,10000]){row=await flags.updateDefinition(db,actor,{key,expectedRevision:row.revision,rolloutBasisPoints:percent});assert.equal(await flags.evaluateBoolean(db,key,{userId:'user-a'}),percent===10000);}
 row=await flags.setOverride(db,actor,{key,expectedRevision:row.revision,targetKind:'user',targetId:'user-a',value:true});const same=await flags.setOverride(db,actor,{key,expectedRevision:row.revision,targetKind:'user',targetId:'user-a',value:true});assert.equal(same.revision,row.revision);row=await flags.setOverride(db,actor,{key,expectedRevision:row.revision,targetKind:'tenant',targetId:'tenant-a',value:false});assert.deepEqual(await flags.evaluateBooleanDetails(db,key,{tenantId:'tenant-a',userId:'user-a'}),{value:false,reason:'tenant-target',revision:row.revision});assert.equal((await flags.evaluateBooleanDetails(db,key,{userId:'user-a'})).reason,'user-target');
 row=await flags.updateDefinition(db,actor,{key,expectedRevision:row.revision,enabled:false});assert.equal((await flags.evaluateBooleanDetails(db,key,{userId:'user-a'})).reason,'disabled');row=await flags.updateDefinition(db,actor,{key,expectedRevision:row.revision,enabled:true});
 const conflicts=await Promise.allSettled([flags.updateDefinition(db,actor,{key,expectedRevision:row.revision,description:'one'}),flags.updateDefinition(db,actor,{key,expectedRevision:row.revision,description:'two'})]);assert.equal(conflicts.filter(r=>r.status==='fulfilled').length,1);row=(await db.select().from(flagDefinitions).where(eq(flagDefinitions.key,key)))[0];
 await assert.rejects(db.transaction(async tx=>{await flags.updateDefinitionInTransaction(tx,actor,{key,expectedRevision:row.revision,enabled:false});throw new Error('fixture rollback');}));assert.equal((await flags.evaluateBooleanDetails(db,key,{userId:'user-a'})).value,true);
 const page=await flags.listOverrides(db,actor,key,{limit:1});assert.equal(page.items.length,1);assert.ok(page.nextCursor);assert.equal((await flags.listOverrides(db,actor,key,{limit:1,cursor:page.nextCursor})).items.length,1);
 row=await flags.removeOverride(db,actor,{key,expectedRevision:row.revision,targetKind:'tenant',targetId:'tenant-a'});const absent=await flags.removeOverride(db,actor,{key,expectedRevision:row.revision,targetKind:'tenant',targetId:'tenant-a'});assert.equal(absent.revision,row.revision);
 await pool.query("UPDATE feature_flag SET description=repeat('x',201) WHERE key=$1",[key]);assert.deepEqual(await flags.evaluateBooleanDetails(db,key,{userId:'user-a'}),{value:false,reason:'error',errorCode:'configuration'});await pool.query("UPDATE feature_flag SET description='' WHERE key=$1",[key]);
 const client=await pool.connect();await client.query('BEGIN');await client.query('LOCK TABLE feature_flag IN ACCESS EXCLUSIVE MODE');assert.equal((await flags.evaluateBooleanDetails(db,key,{userId:'user-a'})).errorCode,'timeout');await client.query('ROLLBACK');client.release();
 await pool.end();pool=undefined;docker('stop',name);pool=new Pool({connectionString:url,connectionTimeoutMillis:1000});const offline=drizzle(pool),failure=await flags.evaluateMany(offline,[key,'unknown.flag'],{});for(const detail of Object.values(failure)){assert.equal(detail.value,false);assert.equal(detail.reason,'error');assert.equal(detail.errorCode,'unavailable');}
 console.log('Feature Flags PostgreSQL contract passed: golden cohorts, precedence, revision/no-op, rollback, bounded batch and fail closed.');
}finally{await pool?.end();try{docker('rm','-f',name);}catch{}}
