import {createHmac,randomUUID} from 'node:crypto';
import {expect,test} from '@playwright/test';
import pg from 'pg';
test('Commerce requires a current session, isolates projections and handles repeated/cancelled requests',async({page,context,request,baseURL})=>{
 const pool=new pg.Pool({connectionString:process.env.E2E_DATABASE_URL??process.env.DATABASE_URL??'postgresql://starter:starter@127.0.0.1:5432/starter'});
 const owner=`medusa-e2e-${randomUUID()}`,foreign=`medusa-e2e-${randomUUID()}`;const binding=randomUUID(),foreignBinding=randomUUID();
 const secret=process.env.BETTER_AUTH_SECRET??'development-only-secret-change-me-now';
 try{
  expect((await request.get('/api/integrations/medusa/products')).status()).toBe(401);await page.goto('/app/medusa');await expect(page).toHaveURL(/\/$|\/?redirect=/);
  for(const id of [owner,foreign])await pool.query('insert into "user"(id,name,email,email_verified,created_at,updated_at) values($1,$2,$3,true,now(),now())',[id,'Commerce fixture',`${id}@example.test`]);
  const now=new Date().toISOString();for(const [id,scope,title] of [[binding,owner,'Bound fixture product'],[foreignBinding,foreign,'PRIVATE_FOREIGN_PRODUCT']]){await pool.query('insert into medusa_binding(id,scope_kind,scope_id,local_resource_id,connection_id,resource_kind,remote_id,created_at) values($1,\'user\',$2,$3,\'default\',\'product\',$3,now())',[id,scope,id]);await pool.query('insert into medusa_projection(binding_id,value,created_at,synced_at) values($1,$2,now(),now())',[id,JSON.stringify({bindingId:id,remoteId:id,title,handle:'fixture',status:'published',sourceUpdatedAt:null,syncedAt:now,deleted:false})]);}
  const token=randomUUID();await pool.query('insert into "session"(id,user_id,token,expires_at,created_at,updated_at) values($1,$2,$3,now()+interval \'1 hour\',now(),now())',[randomUUID(),owner,token]);const cookie=encodeURIComponent(`${token}.${createHmac('sha256',secret).update(token).digest('base64')}`);await context.addCookies([{name:'better-auth.session_token',value:cookie,domain:new URL(baseURL as string).hostname,path:'/',httpOnly:true,sameSite:'Lax'},{name:'__Secure-better-auth.session_token',value:cookie,domain:new URL(baseURL as string).hostname,path:'/',httpOnly:true,sameSite:'Lax',secure:true}]);
  await page.goto('/app/medusa');await expect(page.getByText('Bound fixture product · published')).toBeVisible();expect(await page.content()).not.toContain('PRIVATE_FOREIGN_PRODUCT');
  expect((await context.request.get(`/api/integrations/medusa/product?bindingId=${foreignBinding}`)).status()).toBe(404);
  const listing=await context.request.get('/api/integrations/medusa/products');expect(listing.headers()['cache-control']).toBe('no-store');expect(JSON.stringify(await listing.json())).not.toContain('PRIVATE_FOREIGN_PRODUCT');
  let count=0;let captured:()=>void=()=>{};const ready=new Promise<void>(resolve=>{captured=resolve;});let release:()=>void=()=>{};const gate=new Promise<void>(resolve=>{release=resolve;});
  await page.route('**/api/integrations/medusa/reconcile',async route=>{count++;captured();await gate;try{await route.continue();}catch{}});
  await page.getByRole('button',{name:'Reconcile',exact:true}).dblclick();await ready;expect(count).toBe(1);await expect(page.getByRole('button',{name:'Reconcile',exact:true})).toBeDisabled();await page.getByRole('button',{name:'Stop request',exact:true}).click();release();await expect(page.getByRole('alert')).toHaveText('Request stopped. Refresh to check whether it was queued.');await page.unroute('**/api/integrations/medusa/reconcile');
  await page.getByRole('button',{name:'Reconcile',exact:true}).click();await expect(page.getByRole('alert')).toHaveText('Integration is not configured.');await expect(page.getByRole('button',{name:'Reconcile',exact:true})).toBeEnabled();
  const cancellationId=randomUUID();await pool.query("insert into medusa_operation(id,scope_kind,scope_id,actor_user_id,connection_id,kind,binding_id,caller_key,digest,intent,status,created_at,updated_at) values($1,'user',$2,$2,'default','reconcile_product',$3,$6,$4,$5,'queued',now(),now())",[cancellationId,owner,binding,'0'.repeat(64),JSON.stringify({kind:'product'}),cancellationId]);const cancelled=await context.request.post('/api/integrations/medusa/cancel-operation',{headers:{origin:baseURL as string},data:{operationId:cancellationId}});expect(cancelled.status()).toBe(200);expect((await cancelled.json()).status).toBe('cancelled');
  await context.clearCookies();await page.getByRole('button',{name:'Refresh',exact:true}).click();await expect(page.getByRole('alert')).toHaveText('Authentication required.');expect(await page.content()).not.toContain('Bound fixture product');
 }finally{await pool.query('delete from medusa_inbox where binding_id=any($1)',[[binding,foreignBinding]]);await pool.query('delete from medusa_operation where scope_id=any($1)',[[owner,foreign]]);await pool.query('delete from medusa_projection where binding_id=any($1)',[[binding,foreignBinding]]);await pool.query('delete from medusa_binding where id=any($1)',[[binding,foreignBinding]]);await pool.query('delete from "session" where user_id=any($1)',[[owner,foreign]]);await pool.query('delete from "user" where id=any($1)',[[owner,foreign]]);await pool.end();}
});
