import {createHmac,randomUUID} from "node:crypto";
import {expect,test} from "@playwright/test";
import pg from "pg";
test("Stripe reference restores human session, scopes local status, cancels queued intent and repeats safely without configured provider",async ({page,context,request,baseURL})=>{
 const pool=new pg.Pool({connectionString:process.env.E2E_DATABASE_URL??process.env.DATABASE_URL});const owner=`stripe-e2e-${randomUUID()}`;const other=`stripe-e2e-${randomUUID()}`;const token=randomUUID();const customer=randomUUID();const foreign=randomUUID();const operation=randomUUID();
 try{
  const anonymous=await request.post("/api/integrations/stripe/listPayments",{data:{}});expect(anonymous.status()).toBe(401);expect(anonymous.headers()["cache-control"]).toBe("no-store");
  await page.goto("/app/payments");await expect.poll(()=>new URL(page.url()).pathname).toBe("/");expect(new URL(page.url()).searchParams.get("redirect")).toBe("/app/payments");
  await pool.query('INSERT INTO "user"(id,name,email) VALUES($1,$1,$1||\'@example.test\'),($2,$2,$2||\'@example.test\')',[owner,other]);await pool.query('INSERT INTO session(id,user_id,token,expires_at) VALUES($1,$2,$3,now()+interval \'1 hour\')',[randomUUID(),owner,token]);
  for(const [id,scope,remote] of [[customer,owner,"cus_fixture"],[foreign,other,"cus_foreign"]])await pool.query("insert into stripe_binding(id,scope_kind,scope_id,local_resource_id,connection_id,resource_kind,remote_id,created_at) values ($1::uuid,'user',$2,$1::text,'default','customer',$3,now())",[id,scope,remote]);
  await pool.query("insert into stripe_operation(id,scope_kind,scope_id,actor_user_id,connection_id,kind,caller_key,digest,source_binding_id,status,created_at,updated_at) values ($1,'user',$2,$2,'default','create_checkout','fixture-key',$3,$4,'queued',now(),now())",[operation,owner,"a".repeat(64),customer]);
  const value=encodeURIComponent(`${token}.${createHmac("sha256",process.env.BETTER_AUTH_SECRET??"development-only-secret-change-me-now").update(token).digest("base64")}`);for(const name of ["better-auth.session_token","__Secure-better-auth.session_token"])await context.addCookies([{name,value,domain:new URL(baseURL as string).hostname,path:"/",httpOnly:true,sameSite:"Lax",secure:name.startsWith("__Secure-")}]);
  await page.goto("/app/payments");await expect(page.getByRole("heading",{name:"Payments",exact:true})).toBeVisible();await expect(page.getByText("No reconciled payments yet.")).toBeVisible();
  await page.getByLabel("Operation ID",{exact:true}).fill(operation);await page.getByRole("button",{name:"Refresh status"}).click();await expect(page.getByRole("button",{name:"Cancel queued operation"})).toBeVisible();await page.getByRole("button",{name:"Cancel queued operation"}).click();await expect(page.getByRole("status")).toContainText("Queued operation cancelled.");expect((await pool.query("select status from stripe_operation where id=$1",[operation])).rows[0].status).toBe("cancelled");
  const foreignResponse=await context.request.post("/api/integrations/stripe/requestCheckout",{headers:{origin:baseURL as string},data:{customerBindingId:foreign,idempotencyKey:"foreign",items:[{offerId:"standard",quantity:1}]}});expect(foreignResponse.status()).toBe(404);expect(JSON.stringify(await foreignResponse.json())).not.toContain("cus_foreign");
  const bodies:Record<string,unknown>[]=[];page.on("request",req=>{if(req.url().endsWith("/requestCheckout"))bodies.push(req.postDataJSON());});
  await page.getByLabel("Customer binding",{exact:true}).fill(customer);await page.getByRole("button",{name:"Request Checkout",exact:true}).click();await expect(page.getByRole("status")).toContainText("Integration is not configured.");await page.getByRole("button",{name:"Request Checkout",exact:true}).click();await expect.poll(()=>bodies.length).toBe(2);expect(bodies[0].idempotencyKey).toBe(bodies[1].idempotencyKey);expect(Object.keys(bodies[0]).sort()).toEqual(["customerBindingId","idempotencyKey","items"]);
  expect((await context.request.post("/api/integrations/stripe/listPayments",{headers:{origin:"https://foreign.example"},data:{}})).status()).toBe(403);
 }finally{await pool.query("delete from stripe_operation where id=$1",[operation]);await pool.query("delete from stripe_binding where id=any($1::uuid[])",[[customer,foreign]]);await pool.query('delete from "user" where id=any($1::text[])',[[owner,other]]);await pool.end();}
});
