import * as transferDatabaseSchema from "../src/db/schema";
import { createTransferTransactions } from "../src/integrations/import-export/database.server";
import assert from 'node:assert/strict';
import {spawn} from 'node:child_process';
import {transferConfig} from '../src/integrations/import-export/config.server';
import { randomUUID } from 'node:crypto';
import { Readable } from 'node:stream';
import pg from 'pg';
import { drizzle } from 'drizzle-orm/node-postgres';
import { migrate } from 'drizzle-orm/node-postgres/migrator';
import { eq, sql } from 'drizzle-orm';
import { fromDrizzle, PgBoss } from 'pg-boss';
import { z } from 'zod';
import { createTransfers, transferQueue } from '../src/integrations/import-export/service.server';
import { createTransferRegistry } from '../src/integrations/import-export/registry.server';
import { transfers } from '../src/integrations/import-export/schema';
import { TransferError, type TransferContext } from '../src/integrations/import-export/validation';
import { StorageError } from '../src/integrations/storage/errors.server';
import { createStorage } from '../src/integrations/storage/storage.server';
assert(process.env.DATABASE_URL);
const admin=new pg.Pool({connectionString:process.env.DATABASE_URL});
const name=`transfer_fixture_${randomUUID().replaceAll('-','')}`; const url=new URL(process.env.DATABASE_URL);url.pathname=`/${name}`;
const pool=new pg.Pool({connectionString:url.toString(),connectionTimeoutMillis:5000});
const db=drizzle(pool); const storage=createStorage(); const boss=new PgBoss({connectionString:url.toString(),migrate:true,superviseIntervalSeconds:1,monitorIntervalSeconds:1,maintenanceIntervalSeconds:1});
const owner:TransferContext={requesterId:'fixture-owner',scope:{kind:'user',id:'fixture-owner'}}; const foreign:TransferContext={requesterId:'fixture-other',scope:{kind:'user',id:'fixture-other'}};
let allowed=true; let failSql=false; let failPut=false; let failRead=false; let sleepSql=false; let getGate:(()=>Promise<void>)|undefined; let revokeAfterPut=false; let importGate:(()=>Promise<void>)|undefined; let snapshotGate:(()=>Promise<void>)|undefined;
const fixtureStorage={...storage,async getObject(...args:Parameters<typeof storage.getObject>){const result=await storage.getObject(...args);await getGate?.();if(failRead){(result.body as {destroy?:()=>void})?.destroy?.();throw new StorageError('unavailable');}return result;},async putObject(...args:Parameters<typeof storage.putObject>){const result=await storage.putObject(...args);if(revokeAfterPut)allowed=false;if(failPut)throw new StorageError('unavailable');return result;}};
const registry=createTransferRegistry([{
 name:'projects',version:'1',columns:['name','description'],rowSchema:z.object({name:z.string().trim().min(1).max(120),description:z.string().trim().max(1000)}),
 async authorize(_tx,ctx) { return allowed && (ctx.scope.kind==='user'||['fixture-tenant-a','fixture-tenant-b'].includes(ctx.scope.id)); },
 async importRows(tx,rows,ctx,signal) { for(const raw of rows) {signal.throwIfAborted();const row=z.object({name:z.string(),description:z.string()}).parse(raw);await tx.execute(sql`insert into fixture_project(id,owner_id,name,description) values(${randomUUID()},${ctx.requesterId},${row.name},${row.description})`);if(sleepSql)await tx.execute(sql`select pg_sleep(10)`);if(failSql) throw new Error('private database error');}await importGate?.(); },
 async *exportRows(tx,ctx) { const result=await tx.execute<{name:string;description:string}>(sql`select name,description from fixture_project where owner_id=${ctx.requesterId} order by id`);await snapshotGate?.();const repeat=await tx.execute<{count:string}>(sql`select count(*)::text as count from fixture_project where owner_id=${ctx.requesterId}`);assert.equal(Number(repeat.rows[0].count),result.rows.length);for(const row of result.rows)yield[row.name,row.description]; },
}]);
const service=createTransfers({transaction:createTransferTransactions(()=>url.toString(),transferDatabaseSchema),registry,storage:()=>fixtureStorage,jobs:async()=>boss,enqueue:async(tx,id)=> { const job=await boss.send(transferQueue,{transferId:id},{retryLimit:5,retryDelay:30,retryBackoff:true,retryDelayMax:900,expireInSeconds:transferConfig().timeoutSeconds+30,deleteAfterSeconds:86400,db:fromDrizzle(tx,sql)});assert(job);return job;}});
const stage=(text:string)=>service.stageImport(owner,{definition:'projects',body:Readable.from(Array.from(Buffer.from(text),b=>Buffer.from([b])))});
const rejected=(code:string)=>(e:unknown)=>e instanceof TransferError && e.code===code;
try {
 await admin.query(`CREATE DATABASE "${name}"`);await migrate(db,{migrationsFolder:'drizzle'});
 await pool.query('create table fixture_project(id uuid primary key, owner_id text not null, name text not null,description text)');
 await boss.start();await boss.createQueue(transferQueue,{retryLimit:5,retryDelay:30,retryBackoff:true,retryDelayMax:900,expireInSeconds:90,deleteAfterSeconds:86400});
 const first=await stage('\ufeffname,description\r\n"é","line\n""quoted"""\r\n');assert.equal(first.status,'staged');
 await assert.rejects(service.getTransfer(foreign,first.id),rejected('not-found'));
 await assert.rejects(service.getTransfer({...owner,scope:{kind:'tenant',id:'foreign-tenant'}},first.id),rejected('not-found'));
 const start=await service.startImport(owner,{transferId:first.id,idempotencyKey:'same'});
 assert.deepEqual(await service.startImport(owner,{transferId:first.id,idempotencyKey:'same'}),start);
 await Promise.all([service.run(first.id),service.run(first.id)]);
 assert.equal((await pool.query('select * from fixture_project')).rowCount,1);assert.equal((await service.getTransfer(owner,first.id)).status,'succeeded');
 await service.run(first.id);assert.equal((await pool.query('select * from fixture_project')).rowCount,1);
 await assert.rejects(service.cancelTransfer(owner,first.id),rejected('conflict'));
 const second=await stage('name,description\none,two\n');await assert.rejects(service.startImport(owner,{transferId:second.id,idempotencyKey:'same'}),rejected('conflict'));
 const invalid=await stage('name,description\n,private-cell\n');await service.startImport(owner,{transferId:invalid.id,idempotencyKey:'invalid'});await service.run(invalid.id);assert.equal((await service.getTransfer(owner,invalid.id)).errorCode,'validation-failed');assert.equal((await pool.query('select * from fixture_project')).rowCount,1);
 const rollback=await stage('name,description\none,two\n');await service.startImport(owner,{transferId:rollback.id,idempotencyKey:'rollback'});failSql=true;await service.run(rollback.id);failSql=false;assert.equal((await pool.query('select * from fixture_project')).rowCount,1);
 const revoked=await stage('name,description\none,two\n');await service.startImport(owner,{transferId:revoked.id,idempotencyKey:'revoked'});allowed=false;await service.run(revoked.id);allowed=true;assert.equal((await service.getTransfer(owner,revoked.id)).errorCode,'forbidden');
 const cancelled=await stage('name,description\none,two\n');await service.startImport(owner,{transferId:cancelled.id,idempotencyKey:'cancelled'});await service.cancelTransfer(owner,cancelled.id);await service.cancelTransfer(owner,cancelled.id);await service.run(cancelled.id);assert.equal((await service.getTransfer(owner,cancelled.id)).status,'cancelled');
 const expired=await stage('name,description\none,two\n');await db.update(transfers).set({artifactExpiresAt:new Date(0)}).where(eq(transfers.id,expired.id));await assert.rejects(service.startImport(owner,{transferId:expired.id,idempotencyKey:'expired'}),rejected('expired'));
 const forged=await stage('name,description\none,two\n');await db.update(transfers).set({sourceHash:'0'.repeat(64)}).where(eq(transfers.id,forged.id));await service.startImport(owner,{transferId:forged.id,idempotencyKey:'forged'});await service.run(forged.id);assert.equal((await service.getTransfer(owner,forged.id)).errorCode,'invalid-format');
 const exported=await service.requestExport(owner,{definition:'projects',idempotencyKey:'export'});assert.deepEqual(await service.requestExport(owner,{definition:'projects',idempotencyKey:'export'}),exported);await assert.rejects(service.getExportDownload(owner,exported.id),rejected('conflict'));await service.run(exported.id);const download=await service.getExportDownload(owner,exported.id);assert.equal(download.expiresIn,600);const response=await fetch(download.url);assert.equal(response.status,200);assert.equal(await response.text(),'name,description\r\né,"line\n""quoted"""\r\n');
 await db.update(transfers).set({artifactExpiresAt:new Date(Date.now()+29000)}).where(eq(transfers.id,exported.id));await assert.rejects(service.getExportDownload(owner,exported.id),rejected('expired'));
 const lost=await stage('name,description\none,two\n');await service.startImport(owner,{transferId:lost.id,idempotencyKey:'lost'});const [lostRow]=await db.select().from(transfers).where(eq(transfers.id,lost.id));await boss.deleteJob(transferQueue,lostRow.jobId!);assert.equal((await service.reconcileTransfer(owner,lost.id)).errorCode,'execution-lost');
 const page=await service.listTransfers(owner,{limit:2});assert.equal(page.transfers.length,2);assert(page.cursor);assert.equal((await service.listTransfers(owner,{limit:2,cursor:page.cursor})).transfers.length,2);await assert.rejects(service.listTransfers(owner,{cursor:page.cursor+'='}),rejected('invalid-input'));
 const [artifact]=await db.select().from(transfers).where(eq(transfers.id,exported.id));assert(artifact.outputKey);assert.equal((await service.purgeTransferArtifacts([exported.id]))[0].executed,false);await storage.headObject(artifact.outputKey);await service.purgeTransferArtifacts([exported.id],{execute:true});await assert.rejects(storage.headObject(artifact.outputKey));assert.equal((await service.getTransfer(owner,exported.id)).status,'succeeded');
 // Failed acquisition after an actual PUT leaves a private recorded orphan, never a staged source.
 failPut=true;await assert.rejects(stage('name,description\none,two\n'),rejected('unavailable'));failPut=false;
 const [orphan]=await db.select().from(transfers).where(eq(transfers.errorCode,'unavailable'));assert.equal(orphan.status,'failed');assert(orphan.sourceKey);await storage.headObject(orphan.sourceKey);
 // Actual replacement of a recorded object is detected independently of its ETag.
 const replaced=await stage('name,description\noriginal,two\n');const [replacedRow]=await db.select().from(transfers).where(eq(transfers.id,replaced.id));await storage.putObject(replacedRow.sourceKey!,Buffer.from('name,description\nreplaced,two\n'));await service.startImport(owner,{transferId:replaced.id,idempotencyKey:'replaced'});await service.run(replaced.id);assert.equal((await service.getTransfer(owner,replaced.id)).errorCode,'invalid-format');
 // Import holds the same receipt lock through domain commit; a waiting cancellation observes committed success.
 const race=await stage('name,description\ncommit-wins,two\n');await service.startImport(owner,{transferId:race.id,idempotencyKey:'commit-race'});
 let entered!:()=>void;let release!:()=>void;const applying=new Promise<void>(resolve=>{entered=resolve;});const held=new Promise<void>(resolve=>{release=resolve;});importGate=async()=>{entered();await held;};const running=service.run(race.id);await applying;const cancellation=service.cancelTransfer(owner,race.id);const checked=assert.rejects(cancellation,rejected('conflict'));await new Promise(resolve=>setTimeout(resolve,50));release();await running;await checked;importGate=undefined;assert.equal((await service.getTransfer(owner,race.id)).status,'succeeded');
 // Repeatable-read snapshot does not include a concurrent committed insertion between reads.
 let snapshotEntered!:()=>void;let snapshotRelease!:()=>void;const reading=new Promise<void>(resolve=>{snapshotEntered=resolve;});const readHeld=new Promise<void>(resolve=>{snapshotRelease=resolve;});snapshotGate=async()=>{snapshotEntered();await readHeld;};const consistent=await service.requestExport(owner,{definition:'projects',idempotencyKey:'snapshot-race'});const exporting=service.run(consistent.id);await reading;await pool.query('insert into fixture_project(id,owner_id,name,description) values($1,$2,$3,$4)',[randomUUID(),owner.requesterId,'after-snapshot','private']);snapshotRelease();await exporting;snapshotGate=undefined;const consistentUrl=await service.getExportDownload(owner,consistent.id);assert(!(await (await fetch(consistentUrl.url)).text()).includes('after-snapshot'));
 // Permission revoked after upload prevents pointer publication and fresh bearer URLs.
 const publication=await service.requestExport(owner,{definition:'projects',idempotencyKey:'revoked-publication'});revokeAfterPut=true;await service.run(publication.id);revokeAfterPut=false;allowed=true;const [publicationRow]=await db.select().from(transfers).where(eq(transfers.id,publication.id));assert.equal(publicationRow.errorCode,'forbidden');assert.equal(publicationRow.outputKey,null);assert.equal(publicationRow.artifactKeys.length,1);await assert.rejects(service.getExportDownload(owner,publication.id),rejected('conflict'));
 // Trusted, explicitly authorized tenant contexts remain exact receipt scopes even for the same requester.
 const tenantA:TransferContext={...owner,scope:{kind:'tenant',id:'fixture-tenant-a'}};const tenantB:TransferContext={...owner,scope:{kind:'tenant',id:'fixture-tenant-b'}};const tenantReceipt=await service.stageImport(tenantA,{definition:'projects',body:Readable.from([Buffer.from('name,description\n')])});await assert.rejects(service.getTransfer(tenantB,tenantReceipt.id),rejected('not-found'));await assert.rejects(service.getTransfer({...foreign,scope:tenantA.scope},tenantReceipt.id),rejected('not-found'));await service.startImport(tenantA,{transferId:tenantReceipt.id,idempotencyKey:'tenant-key'});await service.run(tenantReceipt.id);assert.equal((await service.listTransfers(tenantA)).transfers.length,1);assert.equal((await service.listTransfers(tenantB)).transfers.length,0);
 // Cancellation wins before apply while a real acquired S3 body is still held; abort closes that body.
 const cancelBefore=await stage('name,description\ncancel-before-apply,fixture\n');await service.startImport(owner,{transferId:cancelBefore.id,idempotencyKey:'cancel-before-apply'});let acquired!:()=>void;let deliver!:()=>void;const gotBody=new Promise<void>(resolve=>{acquired=resolve;});const heldBody=new Promise<void>(resolve=>{deliver=resolve;});getGate=async()=>{acquired();await heldBody;};const readingSource=service.run(cancelBefore.id);await gotBody;await service.cancelTransfer(owner,cancelBefore.id);deliver();await readingSource;getGate=undefined;assert.equal((await service.getTransfer(owner,cancelBefore.id)).status,'cancelled');assert.equal((await pool.query("select * from fixture_project where name='cancel-before-apply'")).rowCount,0);
 // End-to-end attempt deadline closes active PostgreSQL I/O and rolls back domain writes; retry retains transfer identity.
 const timed=await stage('name,description\ntimeout-rollback,fixture\n');await service.startImport(owner,{transferId:timed.id,idempotencyKey:'attempt-timeout'});const oldTimeout=process.env.IMPORT_EXPORT_TIMEOUT_SECONDS;process.env.IMPORT_EXPORT_TIMEOUT_SECONDS='5';sleepSql=true;const attemptStarted=Date.now();await assert.rejects(service.run(timed.id),rejected('timeout'));assert(Date.now()-attemptStarted<6500);sleepSql=false;if(oldTimeout===undefined)delete process.env.IMPORT_EXPORT_TIMEOUT_SECONDS;else process.env.IMPORT_EXPORT_TIMEOUT_SECONDS=oldTimeout;assert.equal((await pool.query("select * from fixture_project where name='timeout-rollback'")).rowCount,0);assert.equal((await service.getTransfer(owner,timed.id)).status,'pending');await service.run(timed.id);assert.equal((await pool.query("select * from fixture_project where name='timeout-rollback'")).rowCount,1);
 // Native pg-boss retries a transient acquisition failure with the configured delay; receipt remains pending.
 const retry=await stage('name,description\nretry-recovers,two\n');await service.startImport(owner,{transferId:retry.id,idempotencyKey:'native-retry'});const [retryRow]=await db.select().from(transfers).where(eq(transfers.id,retry.id));failRead=true;
 await boss.work(transferQueue,{includeMetadata:true,localConcurrency:1,pollingIntervalSeconds:0.5},async([job])=>service.run((job.data as {transferId:string}).transferId,{id:job.id,signal:job.signal,retryCount:job.retryCount,retryLimit:job.retryLimit}));
 const retryDeadline=Date.now()+10000;let retried=false;while(Date.now()<retryDeadline){const job=await boss.getJobById(transferQueue,retryRow.jobId!);if(job?.state==='retry'){retried=true;break;}await new Promise(resolve=>setTimeout(resolve,100));}assert(retried);assert.equal((await service.getTransfer(owner,retry.id)).status,'pending');failRead=false;
 const completedDeadline=Date.now()+75000;let recovered=false;while(Date.now()<completedDeadline){const job=await boss.getJobById(transferQueue,retryRow.jobId!);if(job?.state==='completed'){assert.equal(job.retryCount,1);recovered=true;break;}await new Promise(resolve=>setTimeout(resolve,250));}assert(recovered);assert.equal((await pool.query("select * from fixture_project where name='retry-recovers'")).rowCount,1);await boss.offWork(transferQueue);
 if(process.env.IMPORT_EXPORT_HARD_CRASH==='1'){
  const previousTimeout=process.env.IMPORT_EXPORT_TIMEOUT_SECONDS;process.env.IMPORT_EXPORT_TIMEOUT_SECONDS='5';const crash=await stage('name,description\nnever-applied,fixture\n');await service.startImport(owner,{transferId:crash.id,idempotencyKey:'hard-crash-exhausted'});if(previousTimeout===undefined)delete process.env.IMPORT_EXPORT_TIMEOUT_SECONDS;else process.env.IMPORT_EXPORT_TIMEOUT_SECONDS=previousTimeout;const [crashRow]=await db.select().from(transfers).where(eq(transfers.id,crash.id));
  for(let attempt=0;attempt<6;attempt++){
   const child=spawn(process.execPath,['scripts/import-export-claim-crash.ts'],{env:{...process.env,DATABASE_URL:url.toString(),IMPORT_EXPORT_FIXTURE_JOB_ID:crashRow.jobId!},stdio:['ignore','pipe','ignore']});
   await new Promise<void>((resolve,reject)=>{const timer=setTimeout(()=>{child.kill('SIGKILL');reject(new Error('Crash fixture claim deadline'));},10000);child.stdout.on('data',chunk=>{if(chunk.toString().includes('fixture.native_claim_ready')){clearTimeout(timer);resolve();}});child.once('exit',()=>{clearTimeout(timer);reject(new Error('Crash fixture claim failed'));});});
   const claimed=await boss.getJobById(transferQueue,crashRow.jobId!);assert.equal(claimed?.state,'active');assert.equal(claimed?.retryCount,attempt);assert.equal(claimed?.retryLimit,5);assert.equal(claimed?.expireInSeconds,35);const exited=new Promise<void>(resolve=>child.once('exit',()=>resolve()));child.kill('SIGKILL');await exited;
   assert.equal((await service.reconcileTransfer(owner,crash.id)).status,'pending');const expiryDeadline=Date.now()+55000;let nativeExpired=false;while(Date.now()<expiryDeadline){const job=await boss.getJobById(transferQueue,crashRow.jobId!);if(job?.state===(attempt===5?'failed':'retry')){nativeExpired=true;break;}await new Promise(resolve=>setTimeout(resolve,250));}assert(nativeExpired);console.info(`fixture.native_hard_crash_attempt_${attempt+1}_expired`);
  }
  assert.equal((await service.reconcileTransfer(owner,crash.id)).status,'failed');assert.equal((await pool.query("select * from fixture_project where name='never-applied'")).rowCount,0);console.info('Six actual killed native claims exhaust the unchanged five-retry policy; receipt-lock reconciliation records terminal failure without domain writes');
 }
 // Invalid lazy worker configuration is a safe terminal result, not an unhandled retry loop.
 const configuration=await stage('name,description\none,two\n');await service.startImport(owner,{transferId:configuration.id,idempotencyKey:'config'});process.env.IMPORT_EXPORT_MAX_ROWS='1e4';await service.run(configuration.id);delete process.env.IMPORT_EXPORT_MAX_ROWS;assert.equal((await service.getTransfer(owner,configuration.id)).errorCode,'configuration');
 console.info('Import/export real PostgreSQL18/pg-boss/S3 contract: scope, UTF8/CSV, idempotency, atomic rollback, duplicate attempts, revocation, cancel, expiry, integrity, export publication, cursor, reconciliation, failed-upload orphan, replaced source, cancellation/commit race, concurrent snapshot, revoked publication, native retry recovery, lazy worker configuration and explicit purge passed');
} finally {
 // Explicit selected fixture-only artifact cleanup; no arbitrary prefix deletion.
 try { const rows=await db.select().from(transfers);for(const row of rows) {if(!['succeeded','failed','cancelled'].includes(row.status)) await db.update(transfers).set({status:'cancelled'}).where(eq(transfers.id,row.id));await service.purgeTransferArtifacts([row.id],{execute:true});} } catch { /* Original fixture failure remains visible. */ }
 storage.close();await boss.stop({graceful:false});await pool.end();await admin.query(`DROP DATABASE IF EXISTS "${name}" WITH (FORCE)`);await admin.end();
}
