import assert from "node:assert/strict";
import { InMemorySpanExporter, SimpleSpanProcessor } from "@opentelemetry/sdk-trace";
import { InMemoryMetricExporter, AggregationTemporality, PeriodicExportingMetricReader } from "@opentelemetry/sdk-metrics";
import { initObservability, flushObservability, shutdownObservability } from "../src/integrations/observability/runtime.server";
import { createCache } from "../src/integrations/cache/cache.server";
import { observeCache } from "../src/lib/cache.server";
const logs: string[] = [];
const spans = new InMemorySpanExporter();
const metrics = new InMemoryMetricExporter(AggregationTemporality.CUMULATIVE);
initObservability({ destination: { write: (line) => logs.push(line) }, registerSignals: false, spanProcessors: [new SimpleSpanProcessor({ exporter: spans })], metricReaders: [new PeriodicExportingMetricReader({ exporter: metrics, exportIntervalMillis: 60000 })] });
const cache = createCache({ env: { CACHE_URL: "rediss://private-user:private-password@private-host", CACHE_KEY_PREFIX: "private-prefix", CACHE_MAX_VALUE_BYTES: "1" }, observe: observeCache });
await assert.rejects(cache.set("private-key", "private-value"));
await assert.rejects(cache.publish("private-channel", "private-message"));
await assert.rejects(cache.releaseLease({ key: "private-lease", token: "private-token" }));
observeCache({ operation: "get", outcome: "success", durationSeconds: 2, hit: false });
await cache.close();
await flushObservability();
const exported = JSON.stringify({ logs: logs.map((line) => JSON.parse(line)), spans: spans.getFinishedSpans().map((span) => ({ name: span.name, attributes: span.attributes, events: span.events })), metrics: metrics.getMetrics() });
for (const secret of ["private-user", "private-password", "private-host", "private-prefix", "private-key", "private-value", "private-channel", "private-message", "private-token", "private-lease", "rediss://"]) assert.ok(!exported.includes(secret));
assert.ok(exported.includes("app.cache.operation.count"));
assert.ok(exported.includes("app.cache.operation.duration"));
assert.ok(exported.includes("app.cache.lookup.count"));
assert.ok(!exported.includes("app.cache.value.size"));
for (const resource of metrics.getMetrics()) for (const scope of resource.scopeMetrics) for (const metric of scope.metrics) for (const point of metric.dataPoints) assert.ok(Object.keys(point.attributes).every((key) => ["app.cache.operation", "app.cache.outcome", "app.cache.hit"].includes(key)));
await shutdownObservability();
console.info("Cache telemetry contains only bounded operations/outcomes, durations, hit/miss");
