import assert from "node:assert/strict";
import { AggregationTemporality, InMemoryMetricExporter, PeriodicExportingMetricReader } from "@opentelemetry/sdk-metrics";
import { InMemorySpanExporter, SimpleSpanProcessor } from "@opentelemetry/sdk-trace";
import { initObservability, flushObservability, shutdownObservability } from "../src/integrations/observability/runtime.server";
import { EmailError } from "../src/integrations/email/errors.server";
import { observeEmail } from "../src/lib/email.server";
const logs: string[] = [], spans = new InMemorySpanExporter(), metrics = new InMemoryMetricExporter(AggregationTemporality.CUMULATIVE);
initObservability({ destination: { write: line => logs.push(line) }, registerSignals: false, spanProcessors: [new SimpleSpanProcessor({ exporter: spans })], metricReaders: [new PeriodicExportingMetricReader({ exporter: metrics, exportIntervalMillis: 60000 })] });
const privateData = { accepted: ["private-recipient@example.test"], rejected: ["private-rejected@example.test"], messageId: "private-message-id", subject: "private-subject", body: "private-body", url: "https://private-host.invalid/?token=private-token", user: "private-smtp-user", password: "private-password" };
await observeEmail({ operation: "send", security: "tls", recipientCount: 2 }, async () => ({ ...privateData, outcome: "partial" as const }));
await observeEmail({ operation: "verify", security: "starttls", recipientCount: 0 }, async () => ({ verified: true }));
await assert.rejects(observeEmail({ operation: "send", security: "opportunistic", recipientCount: 1 }, async () => { throw new EmailError("temporary_rejection", true, privateData); }));
await flushObservability();
const exported = JSON.stringify({ logs: logs.map(line => JSON.parse(line)), spans: spans.getFinishedSpans().map(span => ({ name: span.name, attributes: span.attributes, events: span.events })), metrics: metrics.getMetrics() });
for (const secret of ["private-recipient", "private-rejected", "private-message-id", "private-subject", "private-body", "private-host", "private-token", "private-smtp-user", "private-password"]) assert.ok(!exported.includes(secret));
for (const metric of ["app.email.operation.count", "app.email.operation.duration", "app.email.recipient.count"]) assert.ok(exported.includes(metric));
assert.ok(exported.includes("partial")); assert.ok(exported.includes("failure"));
for (const resource of metrics.getMetrics()) for (const scope of resource.scopeMetrics) for (const metric of scope.metrics) for (const point of metric.dataPoints) assert.deepEqual(Object.keys(point.attributes).sort(), ["app.email.operation", "app.email.outcome", "app.email.security"]);
await shutdownObservability();
console.info("Email logs, spans and metrics contain only bounded operation metadata");
