import assert from 'node:assert/strict';
import {randomUUID} from 'node:crypto';
import {spawn} from 'node:child_process';
import {mkdtemp,mkdir,writeFile,readFile,rm} from 'node:fs/promises';
import {tmpdir} from 'node:os';
import {createServer} from 'node:http';
import {once} from 'node:events';
import pg from 'pg';
import {drizzle} from 'drizzle-orm/node-postgres';
import {migrate} from 'drizzle-orm/node-postgres/migrator';
import * as pgCore from 'drizzle-orm/pg-core';
import {sql} from 'drizzle-orm';
import {PgBoss,fromDrizzle} from 'pg-boss';
import {createMedusa} from '../src/integrations/medusa/medusa.server';
import {createBindingInTransaction} from '../src/integrations/medusa/bindings.server';
import {receiveBridge} from '../src/integrations/medusa/bridge.server';
import {createMedusaJobs} from '../src/integrations/medusa/jobs.server';
Object.keys(pgCore);
process.env.NODE_ENV='test';
const adminUrl=process.env.MEDUSA_FIXTURE_DATABASE_URL??process.env.DATABASE_URL;if(!adminUrl)throw new Error('Explicit disposable fixture database URL required');
const directory=await mkdtemp(`${tmpdir()}/medusa-native-`),prefix=`medusa_native_${randomUUID().replaceAll('-','')}`;
const admin=new pg.Pool({connectionString:adminUrl});const databases=[`${prefix}_provider`,`${prefix}_starter`];for(const name of databases)await admin.query(`create database "${name}"`);
const databaseUrl=(name:string)=>{const u=new URL(adminUrl);u.pathname=`/${name}`;return u.toString();};
const pool=new pg.Pool({connectionString:databaseUrl(databases[1])});const db=drizzle(pool);
const boss=new PgBoss({connectionString:databaseUrl(databases[1]),schema:'medusa_native_jobs',migrate:true,schedule:false,supervise:false});boss.on('error',()=>{});
const token='sk_'+'f'.repeat(64),secret=`whsec_${Buffer.alloc(32,5).toString('base64')}`;
let worker:ReturnType<typeof spawn>|undefined;let provider:ReturnType<typeof spawn>|undefined;let providerUrl='';let eventFailure:unknown;let receiverStatuses:number[]=[];let serverLog='';
const service=createMedusa({db,enqueue:async(tx,payload)=>{await boss.send('medusa.reconcile',payload,{db:fromDrizzle(tx,sql)});},policy:{resolveConnection:async id=>({id,baseUrl:providerUrl,secretApiKey:token,bridgeSecrets:[secret]}),authorizeScope:async(actor,scope)=>scope.kind==='user'&&actor===scope.id,authorizeBoundResource:async(ctx,b)=>ctx.actorUserId===b.scope_id,authorizeMedusaResource:async()=>true,authorizeReconciliation:async()=>true}});
const receiver=createServer(async(req,res)=>{try{const chunks:Buffer[]=[];for await(const chunk of req)chunks.push(Buffer.from(chunk));const r=await receiveBridge(new Request('http://127.0.0.1/bridge',{method:'POST',headers:req.headers as Record<string,string>,body:Buffer.concat(chunks)}),'default',service,db);receiverStatuses.push(r.status);res.writeHead(r.status);res.end(await r.text());}catch(e){eventFailure=e;res.writeHead(503);res.end();}});
receiver.listen(0,'127.0.0.1');await once(receiver,'listening');const address=receiver.address();assert.ok(address&&typeof address==='object');
const environment={...process.env,NODE_ENV:'test',MEDUSA_DISABLE_TELEMETRY:'true',XDG_CONFIG_HOME:`${directory}/config`,MEDUSA_FIXTURE_DATABASE_URL:databaseUrl(databases[0]),MEDUSA_BRIDGE_TARGET_URL:`http://127.0.0.1:${address.port}/api/integrations/medusa/webhooks/default`,MEDUSA_BRIDGE_CONNECTION_ID:'default',MEDUSA_BRIDGE_WEBHOOK_SECRET:secret};
async function run(command:string,args:string[],cwd=directory){const child=spawn(command,args,{cwd,env:environment,stdio:['ignore','pipe','pipe']});let log='';child.stdout?.on('data',b=>{log+=b.toString();});child.stderr?.on('data',b=>{log+=b.toString();});const code=await new Promise<number>((resolve,reject)=>{child.once('error',reject);child.once('exit',c=>resolve(c??1));});if(code!==0)throw new Error(`Pinned Medusa fixture command failed: ${command} ${args.join(' ')} (${code})\n${log.slice(-6000)}`);}
try{
 await migrate(db,{migrationsFolder:'drizzle'});await boss.start();await boss.createQueue('medusa.reconcile',createMedusaJobs(service)['medusa.reconcile'].queue);
 await writeFile(`${directory}/package.json`,JSON.stringify({name:'medusa-pinned-disposable-fixture',private:true,dependencies:{'@medusajs/medusa':'2.21.2','@medusajs/framework':'2.21.2','@medusajs/cli':'2.21.2','ts-node':'10.9.2','typescript':'5.9.3','tsconfig-paths':'4.2.0'}}));
 await run(process.execPath,['install']);
 await writeFile(`${directory}/medusa-config.js`,"const {defineConfig}=require('@medusajs/framework/utils');module.exports=defineConfig({projectConfig:{databaseUrl:process.env.MEDUSA_FIXTURE_DATABASE_URL,http:{jwtSecret:'local-fixture-only',cookieSecret:'local-fixture-only'}},admin:{disable:true}});");
 await mkdir(`${directory}/src/scripts`,{recursive:true});await mkdir(`${directory}/src/subscribers`,{recursive:true});await mkdir(`${directory}/src/api/admin/fixture-probe`,{recursive:true});
 await writeFile(`${directory}/src/scripts/seed.js`,"const {Modules,ContainerRegistrationKeys}=require('@medusajs/framework/utils');const {scryptSync}=require('node:crypto');const {writeFileSync}=require('node:fs');exports.default=async({container})=>{const product=await container.resolve(Modules.PRODUCT).createProducts({title:'Native fixture product',handle:'native-fixture',status:'published'});const order=await container.resolve(Modules.ORDER).createOrders({currency_code:'usd',status:'pending',items:[{title:'Fixture line',quantity:1,unit_price:'123.4567'}]});const key='sk_'+'f'.repeat(64),salt='0'.repeat(32);await container.resolve(ContainerRegistrationKeys.PG_CONNECTION)('api_key').insert({id:'apk_local_test_configuration',token:scryptSync(key,salt,64).toString('hex'),salt,redacted:key.slice(0,6)+'***'+key.slice(-3),title:'Local test configuration',type:'secret',created_by:'fixture'});writeFileSync('seed.json',JSON.stringify({productId:product.id,orderId:order.id}));};");
 // The fixed test-only secret is seeded locally. No provider key-generation API or remote account is used.
 await writeFile(`${directory}/src/api/admin/fixture-probe/route.js`,"const {Modules}=require('@medusajs/framework/utils');const {updateProductsWorkflow}=require('@medusajs/core-flows');const seed=require('../../../../seed.json');exports.POST=async(req,res)=>{await updateProductsWorkflow(req.scope).run({input:{products:[{id:seed.productId,title:'Native updated product'}]}});await req.scope.resolve(Modules.EVENT_BUS).emit({name:'order.placed',data:{id:seed.orderId}});res.json({accepted:true});};");
 const template=await readFile('capabilities/medusa/bridge/subscriber.ts.example','utf8');const adapted=template.replace("'./application-bridge/producer.server'",JSON.stringify(`${process.cwd()}/src/integrations/medusa/producer.server`)).replace("'./application-bridge/contract'",JSON.stringify(`${process.cwd()}/src/integrations/medusa/contract`));await writeFile(`${directory}/subscriber.ts`,adapted);await run(process.execPath,['build',`${directory}/subscriber.ts`,'--target=node','--format=cjs',`--outfile=${directory}/src/subscribers/commerce.js`],process.cwd());
 const cli=`${directory}/node_modules/@medusajs/cli/cli.js`;
 await run('node',[cli,'db:migrate']);await run('node',[cli,'exec','./src/scripts/seed.js']);const seed=JSON.parse(await readFile(`${directory}/seed.json`,'utf8'));
 const portServer=createServer();portServer.listen(0,'127.0.0.1');await once(portServer,'listening');const portAddress=portServer.address();assert.ok(portAddress&&typeof portAddress==='object');const port=portAddress.port;await new Promise<void>(r=>portServer.close(()=>r()));providerUrl=`http://127.0.0.1:${port}`;
 provider=spawn('node',[cli,'start','--port',String(port)],{cwd:directory,env:environment,stdio:['ignore','pipe','pipe']});provider.stdout?.on('data',b=>{serverLog+=b.toString();});provider.stderr?.on('data',b=>{serverLog+=b.toString();});
 await new Promise<void>((resolve,reject)=>{const timer=setTimeout(()=>reject(new Error('Pinned backend did not start: '+serverLog.slice(-4000))),60000);const check=(b:Buffer)=>{if(b.toString().includes('Server is ready')){clearTimeout(timer);resolve();}};provider?.stdout?.on('data',check);provider?.stderr?.on('data',check);provider?.once('exit',()=>{clearTimeout(timer);reject(new Error('Pinned backend exited: '+serverLog.slice(-4000)));});});
 const context={actorUserId:'native-owner',scope:{kind:'user' as const,id:'native-owner'}};
 const product=await db.transaction(tx=>createBindingInTransaction(tx,{scope:context.scope,localResourceId:'native-product',connectionId:'default',kind:'product',remoteId:seed.productId}));const order=await db.transaction(tx=>createBindingInTransaction(tx,{scope:context.scope,localResourceId:'native-order',connectionId:'default',kind:'order',remoteId:seed.orderId}));
 for(const [kind,b] of [['product',product],['order',order]] as const){const op=await service.requestResourceReconciliation(context,{kind,bindingId:b.bindingId});await service.runOperation(op.operationId,AbortSignal.timeout(45000));assert.equal((await service.getOperation(context,{operationId:op.operationId})).status,'succeeded');const page=await service.requestSyncPage(context,{kind,limit:1});await service.runOperation(page.operationId,AbortSignal.timeout(45000));assert.equal((await service.pageResult(context,{operationId:page.operationId})).processed,1);}
 const initial=await service.getOrder(context,order);assert.equal('total' in initial?initial.total:null,'123.4567');
 const result=await fetch(`${providerUrl}/admin/fixture-probe`,{method:'POST',headers:{authorization:`Basic ${Buffer.from(token+':').toString('base64')}`},signal:AbortSignal.timeout(15000)});assert.equal(result.status,200);await result.arrayBuffer();
 // Native in-process subscriber delivery is awaited by polling ONLY this fixture's receipts.
 const end=Date.now()+10000;let events:{id:string;event_type:string}[]=[];while(Date.now()<end){events=(await pool.query("select id,event_type from medusa_inbox where state='received'")).rows;if(events.some(e=>e.event_type==='product.updated')&&events.some(e=>e.event_type==='order.placed'))break;await new Promise(r=>setTimeout(r,50));}
 assert.equal(eventFailure,undefined);assert.ok(events.some(e=>e.event_type==='product.updated'),'native product subscriber hint; receipt statuses='+receiverStatuses.join(',')+'; backend='+serverLog.slice(-4500));assert.ok(events.some(e=>e.event_type==='order.placed'),'source-matched order.placed native event-bus subscriber hint');await run(process.execPath,['build',`${process.cwd()}/scripts/medusa-fixture-worker.ts`,'--target=node',`--outfile=${directory}/worker.mjs`],process.cwd());worker=spawn('node',[`${directory}/worker.mjs`],{cwd:directory,env:{...environment,DATABASE_URL:databaseUrl(databases[1]),PGBOSS_DATABASE_URL:databaseUrl(databases[1]),PGBOSS_SCHEMA:'medusa_native_jobs',MEDUSA_BASE_URL:providerUrl,MEDUSA_SECRET_API_KEY:token},stdio:['ignore','pipe','pipe']});let workerLog='';worker.stdout?.on('data',b=>{workerLog+=b.toString();});worker.stderr?.on('data',b=>{workerLog+=b.toString();});const workerEnd=Date.now()+15000;while(Date.now()<workerEnd){if((await pool.query("select count(*) from medusa_inbox where state='processed'")).rows[0].count===String(events.length))break;if(worker.exitCode!==null)throw new Error('Standalone Medusa fixture worker exited: '+workerLog.slice(-3000));await new Promise(r=>setTimeout(r,50));}assert.equal((await pool.query("select count(*) from medusa_inbox where state='processed'")).rows[0].count,String(events.length));assert.equal((await service.getProduct(context,product) as {title:string}).title,'Native updated product');
 const jobs=(await pool.query("select data from medusa_native_jobs.job where name='medusa.reconcile'")).rows;assert.ok(jobs.length>=events.length);assert.ok(!JSON.stringify(jobs).includes(token));
 console.info(JSON.stringify({fixture:'medusa.native',backend:'2.21.2',adminGet:'passed',subscriberBridge:'passed',standaloneNode24Worker:'passed',orderEvent:'source-matched local event bus; no checkout/payment workflow',outcome:'passed'}));
}finally{
 if(worker&&worker.exitCode===null){worker.kill('SIGTERM');await Promise.race([once(worker,'exit'),new Promise(r=>setTimeout(r,5000))]);if(worker.exitCode===null)worker.kill('SIGKILL');}
 if(provider&&provider.exitCode===null){provider.kill('SIGTERM');await Promise.race([once(provider,'exit'),new Promise(r=>setTimeout(r,5000))]);if(provider.exitCode===null)provider.kill('SIGKILL');}
 receiver.closeAllConnections();await new Promise<void>(resolve=>receiver.close(()=>resolve()));await boss.stop({graceful:false});await pool.end();for(const name of databases)await admin.query(`drop database "${name}" with (force)`);await admin.end();await rm(directory,{recursive:true,force:true});
}
