/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppRouteImport } from './routes/app'
import { Route as ApiHealthRouteImport } from './routes/api/health'
import { Route as ApiOpenapiDotjsonRouteImport } from './routes/api/openapi[.]json'
import { Route as AppApiKeysRouteImport } from './routes/app.api-keys'
import { Route as AppNotificationsRouteImport } from './routes/app.notifications'
import { Route as AppOrganizationsRouteImport } from './routes/app.organizations'
import { Route as AppProjectsRouteImport } from './routes/app.projects'
import { Route as DocsApiRouteImport } from './routes/docs.api'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as ApiV1ProjectsRouteImport } from './routes/api/v1/projects'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiHealthRoute = ApiHealthRouteImport.update({
  id: '/api/health',
  path: '/api/health',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiOpenapiDotjsonRoute = ApiOpenapiDotjsonRouteImport.update({
  id: '/api/openapi.json',
  path: '/api/openapi.json',
  getParentRoute: () => rootRouteImport,
} as any)
const AppApiKeysRoute = AppApiKeysRouteImport.update({
  id: '/api-keys',
  path: '/api-keys',
  getParentRoute: () => AppRoute,
} as any)
const AppNotificationsRoute = AppNotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => AppRoute,
} as any)
const AppOrganizationsRoute = AppOrganizationsRouteImport.update({
  id: '/organizations',
  path: '/organizations',
  getParentRoute: () => AppRoute,
} as any)
const AppProjectsRoute = AppProjectsRouteImport.update({
  id: '/projects',
  path: '/projects',
  getParentRoute: () => AppRoute,
} as any)
const DocsApiRoute = DocsApiRouteImport.update({
  id: '/docs/api',
  path: '/docs/api',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiV1ProjectsRoute = ApiV1ProjectsRouteImport.update({
  id: '/api/v1/projects',
  path: '/api/v1/projects',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/api/health': typeof ApiHealthRoute
  '/api/openapi.json': typeof ApiOpenapiDotjsonRoute
  '/app/api-keys': typeof AppApiKeysRoute
  '/app/notifications': typeof AppNotificationsRoute
  '/app/organizations': typeof AppOrganizationsRoute
  '/app/projects': typeof AppProjectsRoute
  '/docs/api': typeof DocsApiRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/v1/projects': typeof ApiV1ProjectsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/api/health': typeof ApiHealthRoute
  '/api/openapi.json': typeof ApiOpenapiDotjsonRoute
  '/app/api-keys': typeof AppApiKeysRoute
  '/app/notifications': typeof AppNotificationsRoute
  '/app/organizations': typeof AppOrganizationsRoute
  '/app/projects': typeof AppProjectsRoute
  '/docs/api': typeof DocsApiRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/v1/projects': typeof ApiV1ProjectsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/api/health': typeof ApiHealthRoute
  '/api/openapi.json': typeof ApiOpenapiDotjsonRoute
  '/app/api-keys': typeof AppApiKeysRoute
  '/app/notifications': typeof AppNotificationsRoute
  '/app/organizations': typeof AppOrganizationsRoute
  '/app/projects': typeof AppProjectsRoute
  '/docs/api': typeof DocsApiRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/v1/projects': typeof ApiV1ProjectsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/app'
    | '/api/health'
    | '/api/openapi.json'
    | '/app/api-keys'
    | '/app/notifications'
    | '/app/organizations'
    | '/app/projects'
    | '/docs/api'
    | '/api/auth/$'
    | '/api/v1/projects'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/app'
    | '/api/health'
    | '/api/openapi.json'
    | '/app/api-keys'
    | '/app/notifications'
    | '/app/organizations'
    | '/app/projects'
    | '/docs/api'
    | '/api/auth/$'
    | '/api/v1/projects'
  id:
    | '__root__'
    | '/'
    | '/app'
    | '/api/health'
    | '/api/openapi.json'
    | '/app/api-keys'
    | '/app/notifications'
    | '/app/organizations'
    | '/app/projects'
    | '/docs/api'
    | '/api/auth/$'
    | '/api/v1/projects'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  ApiHealthRoute: typeof ApiHealthRoute
  ApiOpenapiDotjsonRoute: typeof ApiOpenapiDotjsonRoute
  DocsApiRoute: typeof DocsApiRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  ApiV1ProjectsRoute: typeof ApiV1ProjectsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/health': {
      id: '/api/health'
      path: '/api/health'
      fullPath: '/api/health'
      preLoaderRoute: typeof ApiHealthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/openapi.json': {
      id: '/api/openapi.json'
      path: '/api/openapi.json'
      fullPath: '/api/openapi.json'
      preLoaderRoute: typeof ApiOpenapiDotjsonRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/api-keys': {
      id: '/app/api-keys'
      path: '/api-keys'
      fullPath: '/app/api-keys'
      preLoaderRoute: typeof AppApiKeysRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/notifications': {
      id: '/app/notifications'
      path: '/notifications'
      fullPath: '/app/notifications'
      preLoaderRoute: typeof AppNotificationsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/organizations': {
      id: '/app/organizations'
      path: '/organizations'
      fullPath: '/app/organizations'
      preLoaderRoute: typeof AppOrganizationsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/projects': {
      id: '/app/projects'
      path: '/projects'
      fullPath: '/app/projects'
      preLoaderRoute: typeof AppProjectsRouteImport
      parentRoute: typeof AppRoute
    }
    '/docs/api': {
      id: '/docs/api'
      path: '/docs/api'
      fullPath: '/docs/api'
      preLoaderRoute: typeof DocsApiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/v1/projects': {
      id: '/api/v1/projects'
      path: '/api/v1/projects'
      fullPath: '/api/v1/projects'
      preLoaderRoute: typeof ApiV1ProjectsRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AppRouteChildren {
  AppApiKeysRoute: typeof AppApiKeysRoute
  AppNotificationsRoute: typeof AppNotificationsRoute
  AppOrganizationsRoute: typeof AppOrganizationsRoute
  AppProjectsRoute: typeof AppProjectsRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppApiKeysRoute: AppApiKeysRoute,
  AppNotificationsRoute: AppNotificationsRoute,
  AppOrganizationsRoute: AppOrganizationsRoute,
  AppProjectsRoute: AppProjectsRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  ApiHealthRoute: ApiHealthRoute,
  ApiOpenapiDotjsonRoute: ApiOpenapiDotjsonRoute,
  DocsApiRoute: DocsApiRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  ApiV1ProjectsRoute: ApiV1ProjectsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
