/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppRouteImport } from './routes/app'
import { Route as ChartsTestRouteImport } from './routes/charts-test'
import { Route as RichTextTestRouteImport } from './routes/rich-text-test'
import { Route as AdminOpsRouteImport } from './routes/admin.ops'
import { Route as ApiHealthRouteImport } from './routes/api/health'
import { Route as ApiOpenapiDotjsonRouteImport } from './routes/api/openapi[.]json'
import { Route as ApiTransfersStageRouteImport } from './routes/api/transfers-stage'
import { Route as AppApiKeysRouteImport } from './routes/app.api-keys'
import { Route as AppInvoicesRouteImport } from './routes/app.invoices'
import { Route as AppMedusaRouteImport } from './routes/app.medusa'
import { Route as AppNotificationsRouteImport } from './routes/app.notifications'
import { Route as AppPaymentsRouteImport } from './routes/app.payments'
import { Route as AppProjectsRouteImport } from './routes/app.projects'
import { Route as AppTransfersRouteImport } from './routes/app.transfers'
import { Route as DocsApiRouteImport } from './routes/docs.api'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as ApiOpsSummaryRouteImport } from './routes/api/ops/summary'
import { Route as ApiV1ProjectsRouteImport } from './routes/api/v1/projects'
import { Route as ApiIntegrationsInvoiceNinjaActionRouteImport } from './routes/api/integrations/invoice-ninja/$action'
import { Route as ApiIntegrationsMedusaSplatRouteImport } from './routes/api/integrations/medusa/$'
import { Route as ApiIntegrationsStripeActionRouteImport } from './routes/api/integrations/stripe/$action'
import { Route as ApiIntegrationsStripeWebhooksConnectionIdRouteImport } from './routes/api/integrations/stripe/webhooks/$connectionId'
import { Route as ApiIntegrationsInvoiceNinjaWebhooksConnectionEventRouteImport } from './routes/api/integrations/invoice-ninja/webhooks/$connection.$event'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const ChartsTestRoute = ChartsTestRouteImport.update({
  id: '/charts-test',
  path: '/charts-test',
  getParentRoute: () => rootRouteImport,
} as any)
const RichTextTestRoute = RichTextTestRouteImport.update({
  id: '/rich-text-test',
  path: '/rich-text-test',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminOpsRoute = AdminOpsRouteImport.update({
  id: '/admin/ops',
  path: '/admin/ops',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiHealthRoute = ApiHealthRouteImport.update({
  id: '/api/health',
  path: '/api/health',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiOpenapiDotjsonRoute = ApiOpenapiDotjsonRouteImport.update({
  id: '/api/openapi.json',
  path: '/api/openapi.json',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiTransfersStageRoute = ApiTransfersStageRouteImport.update({
  id: '/api/transfers-stage',
  path: '/api/transfers-stage',
  getParentRoute: () => rootRouteImport,
} as any)
const AppApiKeysRoute = AppApiKeysRouteImport.update({
  id: '/api-keys',
  path: '/api-keys',
  getParentRoute: () => AppRoute,
} as any)
const AppInvoicesRoute = AppInvoicesRouteImport.update({
  id: '/invoices',
  path: '/invoices',
  getParentRoute: () => AppRoute,
} as any)
const AppMedusaRoute = AppMedusaRouteImport.update({
  id: '/medusa',
  path: '/medusa',
  getParentRoute: () => AppRoute,
} as any)
const AppNotificationsRoute = AppNotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => AppRoute,
} as any)
const AppPaymentsRoute = AppPaymentsRouteImport.update({
  id: '/payments',
  path: '/payments',
  getParentRoute: () => AppRoute,
} as any)
const AppProjectsRoute = AppProjectsRouteImport.update({
  id: '/projects',
  path: '/projects',
  getParentRoute: () => AppRoute,
} as any)
const AppTransfersRoute = AppTransfersRouteImport.update({
  id: '/transfers',
  path: '/transfers',
  getParentRoute: () => AppRoute,
} as any)
const DocsApiRoute = DocsApiRouteImport.update({
  id: '/docs/api',
  path: '/docs/api',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiOpsSummaryRoute = ApiOpsSummaryRouteImport.update({
  id: '/api/ops/summary',
  path: '/api/ops/summary',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiV1ProjectsRoute = ApiV1ProjectsRouteImport.update({
  id: '/api/v1/projects',
  path: '/api/v1/projects',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiIntegrationsInvoiceNinjaActionRoute =
  ApiIntegrationsInvoiceNinjaActionRouteImport.update({
    id: '/api/integrations/invoice-ninja/$action',
    path: '/api/integrations/invoice-ninja/$action',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiIntegrationsMedusaSplatRoute =
  ApiIntegrationsMedusaSplatRouteImport.update({
    id: '/api/integrations/medusa/$',
    path: '/api/integrations/medusa/$',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiIntegrationsStripeActionRoute =
  ApiIntegrationsStripeActionRouteImport.update({
    id: '/api/integrations/stripe/$action',
    path: '/api/integrations/stripe/$action',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiIntegrationsStripeWebhooksConnectionIdRoute =
  ApiIntegrationsStripeWebhooksConnectionIdRouteImport.update({
    id: '/api/integrations/stripe/webhooks/$connectionId',
    path: '/api/integrations/stripe/webhooks/$connectionId',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiIntegrationsInvoiceNinjaWebhooksConnectionEventRoute =
  ApiIntegrationsInvoiceNinjaWebhooksConnectionEventRouteImport.update({
    id: '/api/integrations/invoice-ninja/webhooks/$connection/$event',
    path: '/api/integrations/invoice-ninja/webhooks/$connection/$event',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/charts-test': typeof ChartsTestRoute
  '/rich-text-test': typeof RichTextTestRoute
  '/admin/ops': typeof AdminOpsRoute
  '/api/health': typeof ApiHealthRoute
  '/api/openapi.json': typeof ApiOpenapiDotjsonRoute
  '/api/transfers-stage': typeof ApiTransfersStageRoute
  '/app/api-keys': typeof AppApiKeysRoute
  '/app/invoices': typeof AppInvoicesRoute
  '/app/medusa': typeof AppMedusaRoute
  '/app/notifications': typeof AppNotificationsRoute
  '/app/payments': typeof AppPaymentsRoute
  '/app/projects': typeof AppProjectsRoute
  '/app/transfers': typeof AppTransfersRoute
  '/docs/api': typeof DocsApiRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/ops/summary': typeof ApiOpsSummaryRoute
  '/api/v1/projects': typeof ApiV1ProjectsRoute
  '/api/integrations/invoice-ninja/$action': typeof ApiIntegrationsInvoiceNinjaActionRoute
  '/api/integrations/medusa/$': typeof ApiIntegrationsMedusaSplatRoute
  '/api/integrations/stripe/$action': typeof ApiIntegrationsStripeActionRoute
  '/api/integrations/stripe/webhooks/$connectionId': typeof ApiIntegrationsStripeWebhooksConnectionIdRoute
  '/api/integrations/invoice-ninja/webhooks/$connection/$event': typeof ApiIntegrationsInvoiceNinjaWebhooksConnectionEventRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/charts-test': typeof ChartsTestRoute
  '/rich-text-test': typeof RichTextTestRoute
  '/admin/ops': typeof AdminOpsRoute
  '/api/health': typeof ApiHealthRoute
  '/api/openapi.json': typeof ApiOpenapiDotjsonRoute
  '/api/transfers-stage': typeof ApiTransfersStageRoute
  '/app/api-keys': typeof AppApiKeysRoute
  '/app/invoices': typeof AppInvoicesRoute
  '/app/medusa': typeof AppMedusaRoute
  '/app/notifications': typeof AppNotificationsRoute
  '/app/payments': typeof AppPaymentsRoute
  '/app/projects': typeof AppProjectsRoute
  '/app/transfers': typeof AppTransfersRoute
  '/docs/api': typeof DocsApiRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/ops/summary': typeof ApiOpsSummaryRoute
  '/api/v1/projects': typeof ApiV1ProjectsRoute
  '/api/integrations/invoice-ninja/$action': typeof ApiIntegrationsInvoiceNinjaActionRoute
  '/api/integrations/medusa/$': typeof ApiIntegrationsMedusaSplatRoute
  '/api/integrations/stripe/$action': typeof ApiIntegrationsStripeActionRoute
  '/api/integrations/stripe/webhooks/$connectionId': typeof ApiIntegrationsStripeWebhooksConnectionIdRoute
  '/api/integrations/invoice-ninja/webhooks/$connection/$event': typeof ApiIntegrationsInvoiceNinjaWebhooksConnectionEventRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/charts-test': typeof ChartsTestRoute
  '/rich-text-test': typeof RichTextTestRoute
  '/admin/ops': typeof AdminOpsRoute
  '/api/health': typeof ApiHealthRoute
  '/api/openapi.json': typeof ApiOpenapiDotjsonRoute
  '/api/transfers-stage': typeof ApiTransfersStageRoute
  '/app/api-keys': typeof AppApiKeysRoute
  '/app/invoices': typeof AppInvoicesRoute
  '/app/medusa': typeof AppMedusaRoute
  '/app/notifications': typeof AppNotificationsRoute
  '/app/payments': typeof AppPaymentsRoute
  '/app/projects': typeof AppProjectsRoute
  '/app/transfers': typeof AppTransfersRoute
  '/docs/api': typeof DocsApiRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/ops/summary': typeof ApiOpsSummaryRoute
  '/api/v1/projects': typeof ApiV1ProjectsRoute
  '/api/integrations/invoice-ninja/$action': typeof ApiIntegrationsInvoiceNinjaActionRoute
  '/api/integrations/medusa/$': typeof ApiIntegrationsMedusaSplatRoute
  '/api/integrations/stripe/$action': typeof ApiIntegrationsStripeActionRoute
  '/api/integrations/stripe/webhooks/$connectionId': typeof ApiIntegrationsStripeWebhooksConnectionIdRoute
  '/api/integrations/invoice-ninja/webhooks/$connection/$event': typeof ApiIntegrationsInvoiceNinjaWebhooksConnectionEventRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/app'
    | '/charts-test'
    | '/rich-text-test'
    | '/admin/ops'
    | '/api/health'
    | '/api/openapi.json'
    | '/api/transfers-stage'
    | '/app/api-keys'
    | '/app/invoices'
    | '/app/medusa'
    | '/app/notifications'
    | '/app/payments'
    | '/app/projects'
    | '/app/transfers'
    | '/docs/api'
    | '/api/auth/$'
    | '/api/ops/summary'
    | '/api/v1/projects'
    | '/api/integrations/invoice-ninja/$action'
    | '/api/integrations/medusa/$'
    | '/api/integrations/stripe/$action'
    | '/api/integrations/stripe/webhooks/$connectionId'
    | '/api/integrations/invoice-ninja/webhooks/$connection/$event'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/app'
    | '/charts-test'
    | '/rich-text-test'
    | '/admin/ops'
    | '/api/health'
    | '/api/openapi.json'
    | '/api/transfers-stage'
    | '/app/api-keys'
    | '/app/invoices'
    | '/app/medusa'
    | '/app/notifications'
    | '/app/payments'
    | '/app/projects'
    | '/app/transfers'
    | '/docs/api'
    | '/api/auth/$'
    | '/api/ops/summary'
    | '/api/v1/projects'
    | '/api/integrations/invoice-ninja/$action'
    | '/api/integrations/medusa/$'
    | '/api/integrations/stripe/$action'
    | '/api/integrations/stripe/webhooks/$connectionId'
    | '/api/integrations/invoice-ninja/webhooks/$connection/$event'
  id:
    | '__root__'
    | '/'
    | '/app'
    | '/charts-test'
    | '/rich-text-test'
    | '/admin/ops'
    | '/api/health'
    | '/api/openapi.json'
    | '/api/transfers-stage'
    | '/app/api-keys'
    | '/app/invoices'
    | '/app/medusa'
    | '/app/notifications'
    | '/app/payments'
    | '/app/projects'
    | '/app/transfers'
    | '/docs/api'
    | '/api/auth/$'
    | '/api/ops/summary'
    | '/api/v1/projects'
    | '/api/integrations/invoice-ninja/$action'
    | '/api/integrations/medusa/$'
    | '/api/integrations/stripe/$action'
    | '/api/integrations/stripe/webhooks/$connectionId'
    | '/api/integrations/invoice-ninja/webhooks/$connection/$event'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  ChartsTestRoute: typeof ChartsTestRoute
  RichTextTestRoute: typeof RichTextTestRoute
  AdminOpsRoute: typeof AdminOpsRoute
  ApiHealthRoute: typeof ApiHealthRoute
  ApiOpenapiDotjsonRoute: typeof ApiOpenapiDotjsonRoute
  ApiTransfersStageRoute: typeof ApiTransfersStageRoute
  DocsApiRoute: typeof DocsApiRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  ApiOpsSummaryRoute: typeof ApiOpsSummaryRoute
  ApiV1ProjectsRoute: typeof ApiV1ProjectsRoute
  ApiIntegrationsInvoiceNinjaActionRoute: typeof ApiIntegrationsInvoiceNinjaActionRoute
  ApiIntegrationsMedusaSplatRoute: typeof ApiIntegrationsMedusaSplatRoute
  ApiIntegrationsStripeActionRoute: typeof ApiIntegrationsStripeActionRoute
  ApiIntegrationsStripeWebhooksConnectionIdRoute: typeof ApiIntegrationsStripeWebhooksConnectionIdRoute
  ApiIntegrationsInvoiceNinjaWebhooksConnectionEventRoute: typeof ApiIntegrationsInvoiceNinjaWebhooksConnectionEventRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/charts-test': {
      id: '/charts-test'
      path: '/charts-test'
      fullPath: '/charts-test'
      preLoaderRoute: typeof ChartsTestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rich-text-test': {
      id: '/rich-text-test'
      path: '/rich-text-test'
      fullPath: '/rich-text-test'
      preLoaderRoute: typeof RichTextTestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/ops': {
      id: '/admin/ops'
      path: '/admin/ops'
      fullPath: '/admin/ops'
      preLoaderRoute: typeof AdminOpsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/health': {
      id: '/api/health'
      path: '/api/health'
      fullPath: '/api/health'
      preLoaderRoute: typeof ApiHealthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/openapi.json': {
      id: '/api/openapi.json'
      path: '/api/openapi.json'
      fullPath: '/api/openapi.json'
      preLoaderRoute: typeof ApiOpenapiDotjsonRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/transfers-stage': {
      id: '/api/transfers-stage'
      path: '/api/transfers-stage'
      fullPath: '/api/transfers-stage'
      preLoaderRoute: typeof ApiTransfersStageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/api-keys': {
      id: '/app/api-keys'
      path: '/api-keys'
      fullPath: '/app/api-keys'
      preLoaderRoute: typeof AppApiKeysRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/invoices': {
      id: '/app/invoices'
      path: '/invoices'
      fullPath: '/app/invoices'
      preLoaderRoute: typeof AppInvoicesRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/medusa': {
      id: '/app/medusa'
      path: '/medusa'
      fullPath: '/app/medusa'
      preLoaderRoute: typeof AppMedusaRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/notifications': {
      id: '/app/notifications'
      path: '/notifications'
      fullPath: '/app/notifications'
      preLoaderRoute: typeof AppNotificationsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/payments': {
      id: '/app/payments'
      path: '/payments'
      fullPath: '/app/payments'
      preLoaderRoute: typeof AppPaymentsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/projects': {
      id: '/app/projects'
      path: '/projects'
      fullPath: '/app/projects'
      preLoaderRoute: typeof AppProjectsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/transfers': {
      id: '/app/transfers'
      path: '/transfers'
      fullPath: '/app/transfers'
      preLoaderRoute: typeof AppTransfersRouteImport
      parentRoute: typeof AppRoute
    }
    '/docs/api': {
      id: '/docs/api'
      path: '/docs/api'
      fullPath: '/docs/api'
      preLoaderRoute: typeof DocsApiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/ops/summary': {
      id: '/api/ops/summary'
      path: '/api/ops/summary'
      fullPath: '/api/ops/summary'
      preLoaderRoute: typeof ApiOpsSummaryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/v1/projects': {
      id: '/api/v1/projects'
      path: '/api/v1/projects'
      fullPath: '/api/v1/projects'
      preLoaderRoute: typeof ApiV1ProjectsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/integrations/invoice-ninja/$action': {
      id: '/api/integrations/invoice-ninja/$action'
      path: '/api/integrations/invoice-ninja/$action'
      fullPath: '/api/integrations/invoice-ninja/$action'
      preLoaderRoute: typeof ApiIntegrationsInvoiceNinjaActionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/integrations/medusa/$': {
      id: '/api/integrations/medusa/$'
      path: '/api/integrations/medusa/$'
      fullPath: '/api/integrations/medusa/$'
      preLoaderRoute: typeof ApiIntegrationsMedusaSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/integrations/stripe/$action': {
      id: '/api/integrations/stripe/$action'
      path: '/api/integrations/stripe/$action'
      fullPath: '/api/integrations/stripe/$action'
      preLoaderRoute: typeof ApiIntegrationsStripeActionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/integrations/stripe/webhooks/$connectionId': {
      id: '/api/integrations/stripe/webhooks/$connectionId'
      path: '/api/integrations/stripe/webhooks/$connectionId'
      fullPath: '/api/integrations/stripe/webhooks/$connectionId'
      preLoaderRoute: typeof ApiIntegrationsStripeWebhooksConnectionIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/integrations/invoice-ninja/webhooks/$connection/$event': {
      id: '/api/integrations/invoice-ninja/webhooks/$connection/$event'
      path: '/api/integrations/invoice-ninja/webhooks/$connection/$event'
      fullPath: '/api/integrations/invoice-ninja/webhooks/$connection/$event'
      preLoaderRoute: typeof ApiIntegrationsInvoiceNinjaWebhooksConnectionEventRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AppRouteChildren {
  AppApiKeysRoute: typeof AppApiKeysRoute
  AppInvoicesRoute: typeof AppInvoicesRoute
  AppMedusaRoute: typeof AppMedusaRoute
  AppNotificationsRoute: typeof AppNotificationsRoute
  AppPaymentsRoute: typeof AppPaymentsRoute
  AppProjectsRoute: typeof AppProjectsRoute
  AppTransfersRoute: typeof AppTransfersRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppApiKeysRoute: AppApiKeysRoute,
  AppInvoicesRoute: AppInvoicesRoute,
  AppMedusaRoute: AppMedusaRoute,
  AppNotificationsRoute: AppNotificationsRoute,
  AppPaymentsRoute: AppPaymentsRoute,
  AppProjectsRoute: AppProjectsRoute,
  AppTransfersRoute: AppTransfersRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  ChartsTestRoute: ChartsTestRoute,
  RichTextTestRoute: RichTextTestRoute,
  AdminOpsRoute: AdminOpsRoute,
  ApiHealthRoute: ApiHealthRoute,
  ApiOpenapiDotjsonRoute: ApiOpenapiDotjsonRoute,
  ApiTransfersStageRoute: ApiTransfersStageRoute,
  DocsApiRoute: DocsApiRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  ApiOpsSummaryRoute: ApiOpsSummaryRoute,
  ApiV1ProjectsRoute: ApiV1ProjectsRoute,
  ApiIntegrationsInvoiceNinjaActionRoute:
    ApiIntegrationsInvoiceNinjaActionRoute,
  ApiIntegrationsMedusaSplatRoute: ApiIntegrationsMedusaSplatRoute,
  ApiIntegrationsStripeActionRoute: ApiIntegrationsStripeActionRoute,
  ApiIntegrationsStripeWebhooksConnectionIdRoute:
    ApiIntegrationsStripeWebhooksConnectionIdRoute,
  ApiIntegrationsInvoiceNinjaWebhooksConnectionEventRoute:
    ApiIntegrationsInvoiceNinjaWebhooksConnectionEventRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
